/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import java.time.LocalDateTime

import kotlin.collections.Collection

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.keys.KEY_ADMIN_PASSWORDS_PRIMARY
import net.matsudamper.money.db.schema.tables.records.JAdminPasswordsRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JAdminPasswords(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, JAdminPasswordsRecord>?,
    parentPath: InverseForeignKey<out Record, JAdminPasswordsRecord>?,
    aliased: Table<JAdminPasswordsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<JAdminPasswordsRecord>(
    alias,
    JMoney.MONEY,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>money.admin_passwords</code>
         */
        val ADMIN_PASSWORDS: JAdminPasswords = JAdminPasswords()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JAdminPasswordsRecord> = JAdminPasswordsRecord::class.java

    /**
     * The column <code>money.admin_passwords.id</code>.
     */
    val ID: TableField<JAdminPasswordsRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>money.admin_passwords.password_hash</code>.
     */
    val PASSWORD_HASH: TableField<JAdminPasswordsRecord, String?> = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(512).nullable(false), this, "")

    /**
     * The column <code>money.admin_passwords.salt</code>.
     */
    val SALT: TableField<JAdminPasswordsRecord, ByteArray?> = createField(DSL.name("salt"), SQLDataType.BINARY(32).nullable(false), this, "")

    /**
     * The column <code>money.admin_passwords.algorithm</code>.
     */
    val ALGORITHM: TableField<JAdminPasswordsRecord, String?> = createField(DSL.name("algorithm"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>money.admin_passwords.iteration_count</code>.
     */
    val ITERATION_COUNT: TableField<JAdminPasswordsRecord, Int?> = createField(DSL.name("iteration_count"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.admin_passwords.key_length</code>.
     */
    val KEY_LENGTH: TableField<JAdminPasswordsRecord, Int?> = createField(DSL.name("key_length"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.admin_passwords.created_datetime</code>.
     */
    val CREATED_DATETIME: TableField<JAdminPasswordsRecord, LocalDateTime?> = createField(DSL.name("created_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>money.admin_passwords.update_datetime</code>.
     */
    val UPDATE_DATETIME: TableField<JAdminPasswordsRecord, LocalDateTime?> = createField(DSL.name("update_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<JAdminPasswordsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<JAdminPasswordsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<JAdminPasswordsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>money.admin_passwords</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.admin_passwords</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.admin_passwords</code> table reference
     */
    constructor(): this(DSL.name("admin_passwords"), null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getPrimaryKey(): UniqueKey<JAdminPasswordsRecord> = KEY_ADMIN_PASSWORDS_PRIMARY
    override fun `as`(alias: String): JAdminPasswords = JAdminPasswords(DSL.name(alias), this)
    override fun `as`(alias: Name): JAdminPasswords = JAdminPasswords(alias, this)
    override fun `as`(alias: Table<*>): JAdminPasswords = JAdminPasswords(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JAdminPasswords = JAdminPasswords(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JAdminPasswords = JAdminPasswords(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JAdminPasswords = JAdminPasswords(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): JAdminPasswords = JAdminPasswords(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): JAdminPasswords = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): JAdminPasswords = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): JAdminPasswords = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): JAdminPasswords = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): JAdminPasswords = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JAdminPasswords = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JAdminPasswords = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): JAdminPasswords = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): JAdminPasswords = where(DSL.notExists(select))
}
