/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.indexes.API_TOKENS_USER_ID
import net.matsudamper.money.db.schema.keys.KEY_API_TOKENS_PRIMARY
import net.matsudamper.money.db.schema.keys.KEY_API_TOKENS_TOKEN
import net.matsudamper.money.db.schema.keys.KEY_API_TOKENS_UNIQUE_NAME
import net.matsudamper.money.db.schema.tables.records.JApiTokensRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JApiTokens(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, JApiTokensRecord>?,
    parentPath: InverseForeignKey<out Record, JApiTokensRecord>?,
    aliased: Table<JApiTokensRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<JApiTokensRecord>(
    alias,
    JMoney.MONEY,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>money.api_tokens</code>
         */
        val API_TOKENS: JApiTokens = JApiTokens()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JApiTokensRecord> = JApiTokensRecord::class.java

    /**
     * The column <code>money.api_tokens.api_token_id</code>.
     */
    val API_TOKEN_ID: TableField<JApiTokensRecord, Int?> = createField(DSL.name("api_token_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>money.api_tokens.display_name</code>.
     */
    val DISPLAY_NAME: TableField<JApiTokensRecord, String?> = createField(DSL.name("display_name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>money.api_tokens.user_id</code>.
     */
    val USER_ID: TableField<JApiTokensRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.api_tokens.token_hash</code>.
     */
    val TOKEN_HASH: TableField<JApiTokensRecord, String?> = createField(DSL.name("token_hash"), SQLDataType.VARCHAR(512).nullable(false), this, "")

    /**
     * The column <code>money.api_tokens.permissions</code>.
     */
    val PERMISSIONS: TableField<JApiTokensRecord, String?> = createField(DSL.name("permissions"), SQLDataType.CLOB(65535).nullable(false), this, "")

    /**
     * The column <code>money.api_tokens.expire_datetime</code>.
     */
    val EXPIRE_DATETIME: TableField<JApiTokensRecord, LocalDateTime?> = createField(DSL.name("expire_datetime"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>money.api_tokens.created_datetime</code>.
     */
    val CREATED_DATETIME: TableField<JApiTokensRecord, LocalDateTime?> = createField(DSL.name("created_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>money.api_tokens.update_datetime</code>.
     */
    val UPDATE_DATETIME: TableField<JApiTokensRecord, LocalDateTime?> = createField(DSL.name("update_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<JApiTokensRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<JApiTokensRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<JApiTokensRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>money.api_tokens</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.api_tokens</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.api_tokens</code> table reference
     */
    constructor(): this(DSL.name("api_tokens"), null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getIndexes(): List<Index> = listOf(API_TOKENS_USER_ID)
    override fun getIdentity(): Identity<JApiTokensRecord, Int?> = super.getIdentity() as Identity<JApiTokensRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<JApiTokensRecord> = KEY_API_TOKENS_PRIMARY
    override fun getUniqueKeys(): List<UniqueKey<JApiTokensRecord>> = listOf(KEY_API_TOKENS_TOKEN, KEY_API_TOKENS_UNIQUE_NAME)
    override fun `as`(alias: String): JApiTokens = JApiTokens(DSL.name(alias), this)
    override fun `as`(alias: Name): JApiTokens = JApiTokens(alias, this)
    override fun `as`(alias: Table<*>): JApiTokens = JApiTokens(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JApiTokens = JApiTokens(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JApiTokens = JApiTokens(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JApiTokens = JApiTokens(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): JApiTokens = JApiTokens(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): JApiTokens = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): JApiTokens = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): JApiTokens = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): JApiTokens = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): JApiTokens = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JApiTokens = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JApiTokens = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): JApiTokens = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): JApiTokens = where(DSL.notExists(select))
}
