/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.indexes.CATEGORY_MAIL_FILTER_MATCHERS_CATEGORY_MAIL_FILTER_ID
import net.matsudamper.money.db.schema.indexes.CATEGORY_MAIL_FILTER_MATCHERS_USER_CATEGORY_MAIL_FILTER_MATCHER_ID
import net.matsudamper.money.db.schema.keys.KEY_CATEGORY_MAIL_FILTER_MATCHERS_CATEGORY_MAIL_FILTER_MATCHER_KEY_UNIQUE
import net.matsudamper.money.db.schema.keys.KEY_CATEGORY_MAIL_FILTER_MATCHERS_PRIMARY
import net.matsudamper.money.db.schema.tables.records.JCategoryMailFilterMatchersRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JCategoryMailFilterMatchers(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, JCategoryMailFilterMatchersRecord>?,
    parentPath: InverseForeignKey<out Record, JCategoryMailFilterMatchersRecord>?,
    aliased: Table<JCategoryMailFilterMatchersRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<JCategoryMailFilterMatchersRecord>(
    alias,
    JMoney.MONEY,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of
         * <code>money.category_mail_filter_matchers</code>
         */
        val CATEGORY_MAIL_FILTER_MATCHERS: JCategoryMailFilterMatchers = JCategoryMailFilterMatchers()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JCategoryMailFilterMatchersRecord> = JCategoryMailFilterMatchersRecord::class.java

    /**
     * The column
     * <code>money.category_mail_filter_matchers.category_mail_filter_matcher_id</code>.
     */
    val CATEGORY_MAIL_FILTER_MATCHER_ID: TableField<JCategoryMailFilterMatchersRecord, Int?> = createField(DSL.name("category_mail_filter_matcher_id"), SQLDataType.INTEGER.nullable(false).generatedByDefaultAsIdentity(), this, "")

    /**
     * The column
     * <code>money.category_mail_filter_matchers.category_mail_filter_id</code>.
     */
    val CATEGORY_MAIL_FILTER_ID: TableField<JCategoryMailFilterMatchersRecord, Int?> = createField(DSL.name("category_mail_filter_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.category_mail_filter_matchers.matcher_key</code>.
     */
    val MATCHER_KEY: TableField<JCategoryMailFilterMatchersRecord, String?> = createField(DSL.name("matcher_key"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>money.category_mail_filter_matchers.user_id</code>.
     */
    val USER_ID: TableField<JCategoryMailFilterMatchersRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.category_mail_filter_matchers.text</code>.
     */
    val TEXT: TableField<JCategoryMailFilterMatchersRecord, String?> = createField(DSL.name("text"), SQLDataType.VARCHAR(500).nullable(false), this, "")

    /**
     * The column
     * <code>money.category_mail_filter_matchers.category_mail_filter_datasource_type_id</code>.
     */
    val CATEGORY_MAIL_FILTER_DATASOURCE_TYPE_ID: TableField<JCategoryMailFilterMatchersRecord, Int?> = createField(DSL.name("category_mail_filter_datasource_type_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column
     * <code>money.category_mail_filter_matchers.category_mail_filter_matcher_type_id</code>.
     */
    val CATEGORY_MAIL_FILTER_MATCHER_TYPE_ID: TableField<JCategoryMailFilterMatchersRecord, Int?> = createField(DSL.name("category_mail_filter_matcher_type_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column
     * <code>money.category_mail_filter_matchers.created_datetime</code>.
     */
    val CREATED_DATETIME: TableField<JCategoryMailFilterMatchersRecord, LocalDateTime?> = createField(DSL.name("created_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column
     * <code>money.category_mail_filter_matchers.update_datetime</code>.
     */
    val UPDATE_DATETIME: TableField<JCategoryMailFilterMatchersRecord, LocalDateTime?> = createField(DSL.name("update_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<JCategoryMailFilterMatchersRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<JCategoryMailFilterMatchersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<JCategoryMailFilterMatchersRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>money.category_mail_filter_matchers</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.category_mail_filter_matchers</code> table
     * reference
     */
    constructor(alias: Name): this(alias, CATEGORY_MAIL_FILTER_MATCHERS)

    /**
     * Create a <code>money.category_mail_filter_matchers</code> table reference
     */
    constructor(): this(DSL.name("category_mail_filter_matchers"), null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getIndexes(): List<Index> = listOf(CATEGORY_MAIL_FILTER_MATCHERS_CATEGORY_MAIL_FILTER_ID, CATEGORY_MAIL_FILTER_MATCHERS_USER_CATEGORY_MAIL_FILTER_MATCHER_ID)
    override fun getIdentity(): Identity<JCategoryMailFilterMatchersRecord, Int?> = super.getIdentity() as Identity<JCategoryMailFilterMatchersRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<JCategoryMailFilterMatchersRecord> = KEY_CATEGORY_MAIL_FILTER_MATCHERS_PRIMARY
    override fun getUniqueKeys(): List<UniqueKey<JCategoryMailFilterMatchersRecord>> = listOf(KEY_CATEGORY_MAIL_FILTER_MATCHERS_CATEGORY_MAIL_FILTER_MATCHER_KEY_UNIQUE)
    override fun `as`(alias: String): JCategoryMailFilterMatchers = JCategoryMailFilterMatchers(DSL.name(alias), this)
    override fun `as`(alias: Name): JCategoryMailFilterMatchers = JCategoryMailFilterMatchers(alias, this)
    override fun `as`(alias: Table<*>): JCategoryMailFilterMatchers = JCategoryMailFilterMatchers(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JCategoryMailFilterMatchers = JCategoryMailFilterMatchers(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JCategoryMailFilterMatchers = JCategoryMailFilterMatchers(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JCategoryMailFilterMatchers = JCategoryMailFilterMatchers(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): JCategoryMailFilterMatchers = JCategoryMailFilterMatchers(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): JCategoryMailFilterMatchers = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): JCategoryMailFilterMatchers = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): JCategoryMailFilterMatchers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): JCategoryMailFilterMatchers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): JCategoryMailFilterMatchers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JCategoryMailFilterMatchers = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JCategoryMailFilterMatchers = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): JCategoryMailFilterMatchers = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): JCategoryMailFilterMatchers = where(DSL.notExists(select))
}
