/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import java.util.function.Function

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.keys.KEY_CATEGORY_MAIL_FILTER_CONDITION_TYPE_PRIMARY
import net.matsudamper.money.db.schema.tables.records.JCategoryMailFilterConditionTypeRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JCategoryMailFilterConditionType(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, JCategoryMailFilterConditionTypeRecord>?,
    aliased: Table<JCategoryMailFilterConditionTypeRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<JCategoryMailFilterConditionTypeRecord>(
    alias,
    JMoney.MONEY,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>money.category_mail_filter_condition_type</code>
         */
        val CATEGORY_MAIL_FILTER_CONDITION_TYPE: JCategoryMailFilterConditionType = JCategoryMailFilterConditionType()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JCategoryMailFilterConditionTypeRecord> = JCategoryMailFilterConditionTypeRecord::class.java

    /**
     * The column
     * <code>money.category_mail_filter_condition_type.category_mail_filter_condition_type_id</code>.
     */
    val CATEGORY_MAIL_FILTER_CONDITION_TYPE_ID: TableField<JCategoryMailFilterConditionTypeRecord, Int?> = createField(DSL.name("category_mail_filter_condition_type_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.category_mail_filter_condition_type.name</code>.
     */
    val NAME: TableField<JCategoryMailFilterConditionTypeRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column
     * <code>money.category_mail_filter_condition_type.order_number</code>.
     */
    val ORDER_NUMBER: TableField<JCategoryMailFilterConditionTypeRecord, Int?> = createField(DSL.name("order_number"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<JCategoryMailFilterConditionTypeRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<JCategoryMailFilterConditionTypeRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>money.category_mail_filter_condition_type</code>
     * table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.category_mail_filter_condition_type</code>
     * table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.category_mail_filter_condition_type</code> table
     * reference
     */
    constructor(): this(DSL.name("category_mail_filter_condition_type"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, JCategoryMailFilterConditionTypeRecord>): this(Internal.createPathAlias(child, key), child, key, CATEGORY_MAIL_FILTER_CONDITION_TYPE, null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getPrimaryKey(): UniqueKey<JCategoryMailFilterConditionTypeRecord> = KEY_CATEGORY_MAIL_FILTER_CONDITION_TYPE_PRIMARY
    override fun `as`(alias: String): JCategoryMailFilterConditionType = JCategoryMailFilterConditionType(DSL.name(alias), this)
    override fun `as`(alias: Name): JCategoryMailFilterConditionType = JCategoryMailFilterConditionType(alias, this)
    override fun `as`(alias: Table<*>): JCategoryMailFilterConditionType = JCategoryMailFilterConditionType(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JCategoryMailFilterConditionType = JCategoryMailFilterConditionType(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JCategoryMailFilterConditionType = JCategoryMailFilterConditionType(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JCategoryMailFilterConditionType = JCategoryMailFilterConditionType(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row3<Int?, String?, Int?> = super.fieldsRow() as Row3<Int?, String?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, String?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, String?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
