/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import kotlin.collections.Collection

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.keys.KEY_CATEGORY_MAIL_FILTER_DATASOURCE_TYPE_PRIMARY
import net.matsudamper.money.db.schema.tables.records.JCategoryMailFilterDatasourceTypeRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JCategoryMailFilterDatasourceType(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, JCategoryMailFilterDatasourceTypeRecord>?,
    parentPath: InverseForeignKey<out Record, JCategoryMailFilterDatasourceTypeRecord>?,
    aliased: Table<JCategoryMailFilterDatasourceTypeRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<JCategoryMailFilterDatasourceTypeRecord>(
    alias,
    JMoney.MONEY,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of
         * <code>money.category_mail_filter_datasource_type</code>
         */
        val CATEGORY_MAIL_FILTER_DATASOURCE_TYPE: JCategoryMailFilterDatasourceType = JCategoryMailFilterDatasourceType()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JCategoryMailFilterDatasourceTypeRecord> = JCategoryMailFilterDatasourceTypeRecord::class.java

    /**
     * The column
     * <code>money.category_mail_filter_datasource_type.category_mail_filter_datasource_type_id</code>.
     */
    val CATEGORY_MAIL_FILTER_DATASOURCE_TYPE_ID: TableField<JCategoryMailFilterDatasourceTypeRecord, Int?> = createField(DSL.name("category_mail_filter_datasource_type_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.category_mail_filter_datasource_type.name</code>.
     */
    val NAME: TableField<JCategoryMailFilterDatasourceTypeRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column
     * <code>money.category_mail_filter_datasource_type.order_number</code>.
     */
    val ORDER_NUMBER: TableField<JCategoryMailFilterDatasourceTypeRecord, Int?> = createField(DSL.name("order_number"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<JCategoryMailFilterDatasourceTypeRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<JCategoryMailFilterDatasourceTypeRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<JCategoryMailFilterDatasourceTypeRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>money.category_mail_filter_datasource_type</code>
     * table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.category_mail_filter_datasource_type</code>
     * table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.category_mail_filter_datasource_type</code> table
     * reference
     */
    constructor(): this(DSL.name("category_mail_filter_datasource_type"), null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getPrimaryKey(): UniqueKey<JCategoryMailFilterDatasourceTypeRecord> = KEY_CATEGORY_MAIL_FILTER_DATASOURCE_TYPE_PRIMARY
    override fun `as`(alias: String): JCategoryMailFilterDatasourceType = JCategoryMailFilterDatasourceType(DSL.name(alias), this)
    override fun `as`(alias: Name): JCategoryMailFilterDatasourceType = JCategoryMailFilterDatasourceType(alias, this)
    override fun `as`(alias: Table<*>): JCategoryMailFilterDatasourceType = JCategoryMailFilterDatasourceType(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JCategoryMailFilterDatasourceType = JCategoryMailFilterDatasourceType(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JCategoryMailFilterDatasourceType = JCategoryMailFilterDatasourceType(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JCategoryMailFilterDatasourceType = JCategoryMailFilterDatasourceType(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): JCategoryMailFilterDatasourceType = JCategoryMailFilterDatasourceType(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): JCategoryMailFilterDatasourceType = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): JCategoryMailFilterDatasourceType = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): JCategoryMailFilterDatasourceType = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): JCategoryMailFilterDatasourceType = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): JCategoryMailFilterDatasourceType = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JCategoryMailFilterDatasourceType = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JCategoryMailFilterDatasourceType = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): JCategoryMailFilterDatasourceType = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): JCategoryMailFilterDatasourceType = where(DSL.notExists(select))
}
