/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import kotlin.collections.Collection
import kotlin.collections.List

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.indexes.MONEY_USAGE_IMAGES_RELATION_USER_IMAGE_ID
import net.matsudamper.money.db.schema.indexes.MONEY_USAGE_IMAGES_RELATION_USER_MONEY_USAGE_ID
import net.matsudamper.money.db.schema.keys.KEY_MONEY_USAGE_IMAGES_RELATION_PRIMARY
import net.matsudamper.money.db.schema.tables.records.JMoneyUsageImagesRelationRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JMoneyUsageImagesRelation(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, JMoneyUsageImagesRelationRecord>?,
    parentPath: InverseForeignKey<out Record, JMoneyUsageImagesRelationRecord>?,
    aliased: Table<JMoneyUsageImagesRelationRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<JMoneyUsageImagesRelationRecord>(
    alias,
    JMoney.MONEY,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of
         * <code>money.money_usage_images_relation</code>
         */
        val MONEY_USAGE_IMAGES_RELATION: JMoneyUsageImagesRelation = JMoneyUsageImagesRelation()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JMoneyUsageImagesRelationRecord> = JMoneyUsageImagesRelationRecord::class.java

    /**
     * The column <code>money.money_usage_images_relation.user_id</code>.
     */
    val USER_ID: TableField<JMoneyUsageImagesRelationRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.money_usage_images_relation.money_usage_id</code>.
     */
    val MONEY_USAGE_ID: TableField<JMoneyUsageImagesRelationRecord, Int?> = createField(DSL.name("money_usage_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.money_usage_images_relation.user_image_id</code>.
     */
    val USER_IMAGE_ID: TableField<JMoneyUsageImagesRelationRecord, Int?> = createField(DSL.name("user_image_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.money_usage_images_relation.image_order</code>.
     */
    val IMAGE_ORDER: TableField<JMoneyUsageImagesRelationRecord, Int?> = createField(DSL.name("image_order"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<JMoneyUsageImagesRelationRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<JMoneyUsageImagesRelationRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<JMoneyUsageImagesRelationRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>money.money_usage_images_relation</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.money_usage_images_relation</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.money_usage_images_relation</code> table reference
     */
    constructor(): this(DSL.name("money_usage_images_relation"), null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getIndexes(): List<Index> = listOf(MONEY_USAGE_IMAGES_RELATION_USER_IMAGE_ID, MONEY_USAGE_IMAGES_RELATION_USER_MONEY_USAGE_ID)
    override fun getPrimaryKey(): UniqueKey<JMoneyUsageImagesRelationRecord> = KEY_MONEY_USAGE_IMAGES_RELATION_PRIMARY
    override fun `as`(alias: String): JMoneyUsageImagesRelation = JMoneyUsageImagesRelation(DSL.name(alias), this)
    override fun `as`(alias: Name): JMoneyUsageImagesRelation = JMoneyUsageImagesRelation(alias, this)
    override fun `as`(alias: Table<*>): JMoneyUsageImagesRelation = JMoneyUsageImagesRelation(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JMoneyUsageImagesRelation = JMoneyUsageImagesRelation(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JMoneyUsageImagesRelation = JMoneyUsageImagesRelation(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JMoneyUsageImagesRelation = JMoneyUsageImagesRelation(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): JMoneyUsageImagesRelation = JMoneyUsageImagesRelation(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): JMoneyUsageImagesRelation = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): JMoneyUsageImagesRelation = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): JMoneyUsageImagesRelation = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): JMoneyUsageImagesRelation = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): JMoneyUsageImagesRelation = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JMoneyUsageImagesRelation = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JMoneyUsageImagesRelation = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): JMoneyUsageImagesRelation = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): JMoneyUsageImagesRelation = where(DSL.notExists(select))
}
