/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import java.time.LocalDateTime

import kotlin.collections.Collection

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.keys.KEY_USER_MAIL_AI_PARSE_RESULTS_PRIMARY
import net.matsudamper.money.db.schema.tables.records.JUserMailAiParseResultsRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JUserMailAiParseResults(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, JUserMailAiParseResultsRecord>?,
    parentPath: InverseForeignKey<out Record, JUserMailAiParseResultsRecord>?,
    aliased: Table<JUserMailAiParseResultsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<JUserMailAiParseResultsRecord>(
    alias,
    JMoney.MONEY,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>money.user_mail_ai_parse_results</code>
         */
        val USER_MAIL_AI_PARSE_RESULTS: JUserMailAiParseResults = JUserMailAiParseResults()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JUserMailAiParseResultsRecord> = JUserMailAiParseResultsRecord::class.java

    /**
     * The column <code>money.user_mail_ai_parse_results.user_mail_id</code>.
     */
    val USER_MAIL_ID: TableField<JUserMailAiParseResultsRecord, Int?> = createField(DSL.name("user_mail_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.user_mail_ai_parse_results.user_id</code>.
     */
    val USER_ID: TableField<JUserMailAiParseResultsRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.user_mail_ai_parse_results.status</code>.
     */
    val STATUS: TableField<JUserMailAiParseResultsRecord, String?> = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false), this, "")

    /**
     * The column <code>money.user_mail_ai_parse_results.result_json</code>.
     */
    val RESULT_JSON: TableField<JUserMailAiParseResultsRecord, String?> = createField(DSL.name("result_json"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "")

    /**
     * The column <code>money.user_mail_ai_parse_results.error_message</code>.
     */
    val ERROR_MESSAGE: TableField<JUserMailAiParseResultsRecord, String?> = createField(DSL.name("error_message"), SQLDataType.VARCHAR(1000).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>money.user_mail_ai_parse_results.update_datetime</code>.
     */
    val UPDATE_DATETIME: TableField<JUserMailAiParseResultsRecord, LocalDateTime?> = createField(DSL.name("update_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<JUserMailAiParseResultsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<JUserMailAiParseResultsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<JUserMailAiParseResultsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>money.user_mail_ai_parse_results</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.user_mail_ai_parse_results</code> table reference
     */
    constructor(alias: Name): this(alias, USER_MAIL_AI_PARSE_RESULTS)

    /**
     * Create a <code>money.user_mail_ai_parse_results</code> table reference
     */
    constructor(): this(DSL.name("user_mail_ai_parse_results"), null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getPrimaryKey(): UniqueKey<JUserMailAiParseResultsRecord> = KEY_USER_MAIL_AI_PARSE_RESULTS_PRIMARY
    override fun `as`(alias: String): JUserMailAiParseResults = JUserMailAiParseResults(DSL.name(alias), this)
    override fun `as`(alias: Name): JUserMailAiParseResults = JUserMailAiParseResults(alias, this)
    override fun `as`(alias: Table<*>): JUserMailAiParseResults = JUserMailAiParseResults(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JUserMailAiParseResults = JUserMailAiParseResults(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JUserMailAiParseResults = JUserMailAiParseResults(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JUserMailAiParseResults = JUserMailAiParseResults(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): JUserMailAiParseResults = JUserMailAiParseResults(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): JUserMailAiParseResults = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): JUserMailAiParseResults = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): JUserMailAiParseResults = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): JUserMailAiParseResults = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): JUserMailAiParseResults = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JUserMailAiParseResults = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JUserMailAiParseResults = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): JUserMailAiParseResults = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): JUserMailAiParseResults = where(DSL.notExists(select))
}
