/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.indexes.USER_IMAGES_USER_IMAGE_USER_ID
import net.matsudamper.money.db.schema.keys.KEY_USER_IMAGES_PRIMARY
import net.matsudamper.money.db.schema.keys.KEY_USER_IMAGES_USER_IMAGE_DISPLAY_ID_UNIQUE
import net.matsudamper.money.db.schema.tables.records.JUserImagesRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JUserImages(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, JUserImagesRecord>?,
    parentPath: InverseForeignKey<out Record, JUserImagesRecord>?,
    aliased: Table<JUserImagesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<JUserImagesRecord>(
    alias,
    JMoney.MONEY,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>money.user_images</code>
         */
        val USER_IMAGES: JUserImages = JUserImages()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JUserImagesRecord> = JUserImagesRecord::class.java

    /**
     * The column <code>money.user_images.image_id</code>.
     */
    val IMAGE_ID: TableField<JUserImagesRecord, Int?> = createField(DSL.name("image_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>money.user_images.user_id</code>.
     */
    val USER_ID: TableField<JUserImagesRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.user_images.display_id</code>.
     */
    val DISPLAY_ID: TableField<JUserImagesRecord, String?> = createField(DSL.name("display_id"), SQLDataType.CHAR(36).nullable(false), this, "")

    /**
     * The column <code>money.user_images.image_path</code>.
     */
    val IMAGE_PATH: TableField<JUserImagesRecord, String?> = createField(DSL.name("image_path"), SQLDataType.VARCHAR(1000).nullable(false), this, "")

    /**
     * The column <code>money.user_images.created_datetime</code>.
     */
    val CREATED_DATETIME: TableField<JUserImagesRecord, LocalDateTime?> = createField(DSL.name("created_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<JUserImagesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<JUserImagesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<JUserImagesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>money.user_images</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.user_images</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.user_images</code> table reference
     */
    constructor(): this(DSL.name("user_images"), null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getIndexes(): List<Index> = listOf(USER_IMAGES_USER_IMAGE_USER_ID)
    override fun getIdentity(): Identity<JUserImagesRecord, Int?> = super.getIdentity() as Identity<JUserImagesRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<JUserImagesRecord> = KEY_USER_IMAGES_PRIMARY
    override fun getUniqueKeys(): List<UniqueKey<JUserImagesRecord>> = listOf(KEY_USER_IMAGES_USER_IMAGE_DISPLAY_ID_UNIQUE)
    override fun `as`(alias: String): JUserImages = JUserImages(DSL.name(alias), this)
    override fun `as`(alias: Name): JUserImages = JUserImages(alias, this)
    override fun `as`(alias: Table<*>): JUserImages = JUserImages(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JUserImages = JUserImages(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JUserImages = JUserImages(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JUserImages = JUserImages(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): JUserImages = JUserImages(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): JUserImages = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): JUserImages = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): JUserImages = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): JUserImages = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): JUserImages = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JUserImages = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JUserImages = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): JUserImages = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): JUserImages = where(DSL.notExists(select))
}
