/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import java.time.LocalDateTime
import java.util.function.Function

import kotlin.collections.List

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.indexes.USERS_USER_NAME
import net.matsudamper.money.db.schema.keys.KEY_USERS_PRIMARY
import net.matsudamper.money.db.schema.keys.KEY_USERS_USER_NAME_UNIQUE
import net.matsudamper.money.db.schema.tables.records.JUsersRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JUsers(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, JUsersRecord>?,
    aliased: Table<JUsersRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<JUsersRecord>(
    alias,
    JMoney.MONEY,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>money.users</code>
         */
        val USERS: JUsers = JUsers()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JUsersRecord> = JUsersRecord::class.java

    /**
     * The column <code>money.users.user_id</code>.
     */
    val USER_ID: TableField<JUsersRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>money.users.user_name</code>.
     */
    val USER_NAME: TableField<JUsersRecord, String?> = createField(DSL.name("user_name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>money.users.created_datetime</code>.
     */
    val CREATED_DATETIME: TableField<JUsersRecord, LocalDateTime?> = createField(DSL.name("created_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<JUsersRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<JUsersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>money.users</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.users</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.users</code> table reference
     */
    constructor(): this(DSL.name("users"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, JUsersRecord>): this(Internal.createPathAlias(child, key), child, key, USERS, null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getIndexes(): List<Index> = listOf(USERS_USER_NAME)
    override fun getIdentity(): Identity<JUsersRecord, Int?> = super.getIdentity() as Identity<JUsersRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<JUsersRecord> = KEY_USERS_PRIMARY
    override fun getUniqueKeys(): List<UniqueKey<JUsersRecord>> = listOf(KEY_USERS_USER_NAME_UNIQUE)
    override fun `as`(alias: String): JUsers = JUsers(DSL.name(alias), this)
    override fun `as`(alias: Name): JUsers = JUsers(alias, this)
    override fun `as`(alias: Table<*>): JUsers = JUsers(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JUsers = JUsers(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JUsers = JUsers(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JUsers = JUsers(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row3<Int?, String?, LocalDateTime?> = super.fieldsRow() as Row3<Int?, String?, LocalDateTime?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, String?, LocalDateTime?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, String?, LocalDateTime?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
