/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import kotlin.collections.Collection

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.keys.KEY_USER_IMAP_SETTINGS_PRIMARY
import net.matsudamper.money.db.schema.tables.records.JUserImapSettingsRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JUserImapSettings(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, JUserImapSettingsRecord>?,
    parentPath: InverseForeignKey<out Record, JUserImapSettingsRecord>?,
    aliased: Table<JUserImapSettingsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<JUserImapSettingsRecord>(
    alias,
    JMoney.MONEY,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>money.user_imap_settings</code>
         */
        val USER_IMAP_SETTINGS: JUserImapSettings = JUserImapSettings()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JUserImapSettingsRecord> = JUserImapSettingsRecord::class.java

    /**
     * The column <code>money.user_imap_settings.user_id</code>.
     */
    val USER_ID: TableField<JUserImapSettingsRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.user_imap_settings.host</code>.
     */
    val HOST: TableField<JUserImapSettingsRecord, String?> = createField(DSL.name("host"), SQLDataType.VARCHAR(500).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>money.user_imap_settings.port</code>.
     */
    val PORT: TableField<JUserImapSettingsRecord, Int?> = createField(DSL.name("port"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>money.user_imap_settings.use_name</code>.
     */
    val USE_NAME: TableField<JUserImapSettingsRecord, String?> = createField(DSL.name("use_name"), SQLDataType.VARCHAR(500).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>money.user_imap_settings.password</code>.
     */
    val PASSWORD: TableField<JUserImapSettingsRecord, String?> = createField(DSL.name("password"), SQLDataType.VARCHAR(500).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    private constructor(alias: Name, aliased: Table<JUserImapSettingsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<JUserImapSettingsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<JUserImapSettingsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>money.user_imap_settings</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.user_imap_settings</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.user_imap_settings</code> table reference
     */
    constructor(): this(DSL.name("user_imap_settings"), null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getPrimaryKey(): UniqueKey<JUserImapSettingsRecord> = KEY_USER_IMAP_SETTINGS_PRIMARY
    override fun `as`(alias: String): JUserImapSettings = JUserImapSettings(DSL.name(alias), this)
    override fun `as`(alias: Name): JUserImapSettings = JUserImapSettings(alias, this)
    override fun `as`(alias: Table<*>): JUserImapSettings = JUserImapSettings(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JUserImapSettings = JUserImapSettings(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JUserImapSettings = JUserImapSettings(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JUserImapSettings = JUserImapSettings(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): JUserImapSettings = JUserImapSettings(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): JUserImapSettings = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): JUserImapSettings = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): JUserImapSettings = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): JUserImapSettings = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): JUserImapSettings = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JUserImapSettings = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JUserImapSettings = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): JUserImapSettings = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): JUserImapSettings = where(DSL.notExists(select))
}
