/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import kotlin.collections.Collection

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.keys.KEY_USER_GEMINI_SETTINGS_PRIMARY
import net.matsudamper.money.db.schema.tables.records.JUserGeminiSettingsRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JUserGeminiSettings(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, JUserGeminiSettingsRecord>?,
    parentPath: InverseForeignKey<out Record, JUserGeminiSettingsRecord>?,
    aliased: Table<JUserGeminiSettingsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<JUserGeminiSettingsRecord>(
    alias,
    JMoney.MONEY,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>money.user_gemini_settings</code>
         */
        val USER_GEMINI_SETTINGS: JUserGeminiSettings = JUserGeminiSettings()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JUserGeminiSettingsRecord> = JUserGeminiSettingsRecord::class.java

    /**
     * The column <code>money.user_gemini_settings.user_id</code>.
     */
    val USER_ID: TableField<JUserGeminiSettingsRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.user_gemini_settings.api_key</code>.
     */
    val API_KEY: TableField<JUserGeminiSettingsRecord, String?> = createField(DSL.name("api_key"), SQLDataType.VARCHAR(500).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    private constructor(alias: Name, aliased: Table<JUserGeminiSettingsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<JUserGeminiSettingsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<JUserGeminiSettingsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>money.user_gemini_settings</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.user_gemini_settings</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.user_gemini_settings</code> table reference
     */
    constructor(): this(DSL.name("user_gemini_settings"), null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getPrimaryKey(): UniqueKey<JUserGeminiSettingsRecord> = KEY_USER_GEMINI_SETTINGS_PRIMARY
    override fun `as`(alias: String): JUserGeminiSettings = JUserGeminiSettings(DSL.name(alias), this)
    override fun `as`(alias: Name): JUserGeminiSettings = JUserGeminiSettings(alias, this)
    override fun `as`(alias: Table<*>): JUserGeminiSettings = JUserGeminiSettings(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JUserGeminiSettings = JUserGeminiSettings(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JUserGeminiSettings = JUserGeminiSettings(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JUserGeminiSettings = JUserGeminiSettings(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): JUserGeminiSettings = JUserGeminiSettings(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): JUserGeminiSettings = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): JUserGeminiSettings = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): JUserGeminiSettings = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): JUserGeminiSettings = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): JUserGeminiSettings = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JUserGeminiSettings = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JUserGeminiSettings = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): JUserGeminiSettings = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): JUserGeminiSettings = where(DSL.notExists(select))
}
