/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.keys.KEY_WEB_AUTH_AUTHENTICATOR_PRIMARY
import net.matsudamper.money.db.schema.keys.KEY_WEB_AUTH_AUTHENTICATOR_USER_ID_AND_NAME
import net.matsudamper.money.db.schema.tables.records.JWebAuthAuthenticatorRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JWebAuthAuthenticator(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, JWebAuthAuthenticatorRecord>?,
    parentPath: InverseForeignKey<out Record, JWebAuthAuthenticatorRecord>?,
    aliased: Table<JWebAuthAuthenticatorRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<JWebAuthAuthenticatorRecord>(
    alias,
    JMoney.MONEY,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>money.web_auth_authenticator</code>
         */
        val WEB_AUTH_AUTHENTICATOR: JWebAuthAuthenticator = JWebAuthAuthenticator()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JWebAuthAuthenticatorRecord> = JWebAuthAuthenticatorRecord::class.java

    /**
     * The column <code>money.web_auth_authenticator.id</code>.
     */
    val ID: TableField<JWebAuthAuthenticatorRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>money.web_auth_authenticator.user_id</code>.
     */
    val USER_ID: TableField<JWebAuthAuthenticatorRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.web_auth_authenticator.name</code>.
     */
    val NAME: TableField<JWebAuthAuthenticatorRecord, String?> = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column
     * <code>money.web_auth_authenticator.attestation_statement</code>.
     */
    val ATTESTATION_STATEMENT: TableField<JWebAuthAuthenticatorRecord, String?> = createField(DSL.name("attestation_statement"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column
     * <code>money.web_auth_authenticator.attestation_statement_format</code>.
     */
    val ATTESTATION_STATEMENT_FORMAT: TableField<JWebAuthAuthenticatorRecord, String?> = createField(DSL.name("attestation_statement_format"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column
     * <code>money.web_auth_authenticator.attested_credential_data</code>.
     */
    val ATTESTED_CREDENTIAL_DATA: TableField<JWebAuthAuthenticatorRecord, String?> = createField(DSL.name("attested_credential_data"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column
     * <code>money.web_auth_authenticator.authenticator_extensions</code>.
     */
    val AUTHENTICATOR_EXTENSIONS: TableField<JWebAuthAuthenticatorRecord, String?> = createField(DSL.name("authenticator_extensions"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "")

    /**
     * The column <code>money.web_auth_authenticator.counter</code>.
     */
    val COUNTER: TableField<JWebAuthAuthenticatorRecord, Long?> = createField(DSL.name("counter"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>money.web_auth_authenticator.created_at</code>.
     */
    val CREATED_AT: TableField<JWebAuthAuthenticatorRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>money.web_auth_authenticator.updated_at</code>.
     */
    val UPDATED_AT: TableField<JWebAuthAuthenticatorRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<JWebAuthAuthenticatorRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<JWebAuthAuthenticatorRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<JWebAuthAuthenticatorRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>money.web_auth_authenticator</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.web_auth_authenticator</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.web_auth_authenticator</code> table reference
     */
    constructor(): this(DSL.name("web_auth_authenticator"), null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getIdentity(): Identity<JWebAuthAuthenticatorRecord, Int?> = super.getIdentity() as Identity<JWebAuthAuthenticatorRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<JWebAuthAuthenticatorRecord> = KEY_WEB_AUTH_AUTHENTICATOR_PRIMARY
    override fun getUniqueKeys(): List<UniqueKey<JWebAuthAuthenticatorRecord>> = listOf(KEY_WEB_AUTH_AUTHENTICATOR_USER_ID_AND_NAME)
    override fun `as`(alias: String): JWebAuthAuthenticator = JWebAuthAuthenticator(DSL.name(alias), this)
    override fun `as`(alias: Name): JWebAuthAuthenticator = JWebAuthAuthenticator(alias, this)
    override fun `as`(alias: Table<*>): JWebAuthAuthenticator = JWebAuthAuthenticator(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JWebAuthAuthenticator = JWebAuthAuthenticator(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JWebAuthAuthenticator = JWebAuthAuthenticator(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JWebAuthAuthenticator = JWebAuthAuthenticator(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): JWebAuthAuthenticator = JWebAuthAuthenticator(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): JWebAuthAuthenticator = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): JWebAuthAuthenticator = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): JWebAuthAuthenticator = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): JWebAuthAuthenticator = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): JWebAuthAuthenticator = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JWebAuthAuthenticator = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JWebAuthAuthenticator = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): JWebAuthAuthenticator = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): JWebAuthAuthenticator = where(DSL.notExists(select))
}
