/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import java.time.LocalDateTime

import net.matsudamper.money.db.schema.tables.JAdminPasswords

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JAdminPasswordsRecord() : UpdatableRecordImpl<JAdminPasswordsRecord>(JAdminPasswords.ADMIN_PASSWORDS) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var passwordHash: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var salt: ByteArray?
        set(value): Unit = set(2, value)
        get(): ByteArray? = get(2) as ByteArray?

    open var algorithm: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var iterationCount: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var keyLength: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var createdDatetime: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var updateDatetime: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised JAdminPasswordsRecord
     */
    constructor(id: Int? = null, passwordHash: String? = null, salt: ByteArray? = null, algorithm: String? = null, iterationCount: Int? = null, keyLength: Int? = null, createdDatetime: LocalDateTime? = null, updateDatetime: LocalDateTime? = null): this() {
        this.id = id
        this.passwordHash = passwordHash
        this.salt = salt
        this.algorithm = algorithm
        this.iterationCount = iterationCount
        this.keyLength = keyLength
        this.createdDatetime = createdDatetime
        this.updateDatetime = updateDatetime
        resetTouchedOnNotNull()
    }
}
