/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import java.time.LocalDateTime

import net.matsudamper.money.db.schema.tables.JApiTokens

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JApiTokensRecord() : UpdatableRecordImpl<JApiTokensRecord>(JApiTokens.API_TOKENS) {

    open var apiTokenId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var userId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var tokenHash: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var salt: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var iterationCount: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var algorithm: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var keyLength: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    open var permissions: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var createdDatetime: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    open var updateDatetime: LocalDateTime?
        set(value): Unit = set(9, value)
        get(): LocalDateTime? = get(9) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised JApiTokensRecord
     */
    constructor(apiTokenId: Int? = null, userId: Int? = null, tokenHash: String? = null, salt: String? = null, iterationCount: Int? = null, algorithm: String? = null, keyLength: Int? = null, permissions: String? = null, createdDatetime: LocalDateTime? = null, updateDatetime: LocalDateTime? = null): this() {
        this.apiTokenId = apiTokenId
        this.userId = userId
        this.tokenHash = tokenHash
        this.salt = salt
        this.iterationCount = iterationCount
        this.algorithm = algorithm
        this.keyLength = keyLength
        this.permissions = permissions
        this.createdDatetime = createdDatetime
        this.updateDatetime = updateDatetime
        resetChangedOnNotNull()
    }
}
