/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import java.time.LocalDateTime

import net.matsudamper.money.db.schema.tables.JCategoryMailFilterConditions

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JCategoryMailFilterConditionsRecord() : UpdatableRecordImpl<JCategoryMailFilterConditionsRecord>(JCategoryMailFilterConditions.CATEGORY_MAIL_FILTER_CONDITIONS) {

    open var categoryMailFilterConditionId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var categoryMailFilterId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var userId: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var text: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var categoryMailFilterDatasourceTypeId: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var categoryMailFilterConditionTypeId: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var createdDatetime: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var updateDatetime: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised JCategoryMailFilterConditionsRecord
     */
    constructor(categoryMailFilterConditionId: Int? = null, categoryMailFilterId: Int? = null, userId: Int? = null, text: String? = null, categoryMailFilterDatasourceTypeId: Int? = null, categoryMailFilterConditionTypeId: Int? = null, createdDatetime: LocalDateTime? = null, updateDatetime: LocalDateTime? = null): this() {
        this.categoryMailFilterConditionId = categoryMailFilterConditionId
        this.categoryMailFilterId = categoryMailFilterId
        this.userId = userId
        this.text = text
        this.categoryMailFilterDatasourceTypeId = categoryMailFilterDatasourceTypeId
        this.categoryMailFilterConditionTypeId = categoryMailFilterConditionTypeId
        this.createdDatetime = createdDatetime
        this.updateDatetime = updateDatetime
        resetTouchedOnNotNull()
    }
}
