/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import java.time.LocalDateTime

import net.matsudamper.money.db.schema.tables.JCategoryMailFilters

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JCategoryMailFiltersRecord() : UpdatableRecordImpl<JCategoryMailFiltersRecord>(JCategoryMailFilters.CATEGORY_MAIL_FILTERS) {

    open var categoryMailFilterId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var userId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var title: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var moneyUsageSubCategoryId: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var categoryMailFilterConditionOperatorTypeId: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var createdDatetime: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var updateDatetime: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var orderNumber: Int?
        set(value): Unit = set(7, value)
        get(): Int? = get(7) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised JCategoryMailFiltersRecord
     */
    constructor(categoryMailFilterId: Int? = null, userId: Int? = null, title: String? = null, moneyUsageSubCategoryId: Int? = null, categoryMailFilterConditionOperatorTypeId: Int? = null, createdDatetime: LocalDateTime? = null, updateDatetime: LocalDateTime? = null, orderNumber: Int? = null): this() {
        this.categoryMailFilterId = categoryMailFilterId
        this.userId = userId
        this.title = title
        this.moneyUsageSubCategoryId = moneyUsageSubCategoryId
        this.categoryMailFilterConditionOperatorTypeId = categoryMailFilterConditionOperatorTypeId
        this.createdDatetime = createdDatetime
        this.updateDatetime = updateDatetime
        this.orderNumber = orderNumber
        resetChangedOnNotNull()
    }
}
