/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import net.matsudamper.money.db.schema.tables.JCategoryMailFilterConditionOperatorType

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JCategoryMailFilterConditionOperatorTypeRecord() : UpdatableRecordImpl<JCategoryMailFilterConditionOperatorTypeRecord>(JCategoryMailFilterConditionOperatorType.CATEGORY_MAIL_FILTER_CONDITION_OPERATOR_TYPE) {

    open var categoryMailFilterConditionOperatorTypeId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var operatorName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised
     * JCategoryMailFilterConditionOperatorTypeRecord
     */
    constructor(categoryMailFilterConditionOperatorTypeId: Int? = null, operatorName: String? = null): this() {
        this.categoryMailFilterConditionOperatorTypeId = categoryMailFilterConditionOperatorTypeId
        this.operatorName = operatorName
        resetTouchedOnNotNull()
    }
}
