/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import net.matsudamper.money.db.schema.tables.JCategoryMailFilterConditionType

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JCategoryMailFilterConditionTypeRecord() : UpdatableRecordImpl<JCategoryMailFilterConditionTypeRecord>(JCategoryMailFilterConditionType.CATEGORY_MAIL_FILTER_CONDITION_TYPE) {

    open var categoryMailFilterConditionTypeId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var orderNumber: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised JCategoryMailFilterConditionTypeRecord
     */
    constructor(categoryMailFilterConditionTypeId: Int? = null, name: String? = null, orderNumber: Int? = null): this() {
        this.categoryMailFilterConditionTypeId = categoryMailFilterConditionTypeId
        this.name = name
        this.orderNumber = orderNumber
        resetTouchedOnNotNull()
    }
}
