/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import java.time.LocalDateTime

import net.matsudamper.money.db.schema.tables.JMoneyUsages

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JMoneyUsagesRecord() : UpdatableRecordImpl<JMoneyUsagesRecord>(JMoneyUsages.MONEY_USAGES) {

    open var moneyUsageId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var userId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var title: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var description: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var moneyUsageSubCategoryId: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var datetime: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var createdDatetime: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var updateDatetime: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    open var amount: Int?
        set(value): Unit = set(8, value)
        get(): Int? = get(8) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised JMoneyUsagesRecord
     */
    constructor(moneyUsageId: Int? = null, userId: Int? = null, title: String? = null, description: String? = null, moneyUsageSubCategoryId: Int? = null, datetime: LocalDateTime? = null, createdDatetime: LocalDateTime? = null, updateDatetime: LocalDateTime? = null, amount: Int? = null): this() {
        this.moneyUsageId = moneyUsageId
        this.userId = userId
        this.title = title
        this.description = description
        this.moneyUsageSubCategoryId = moneyUsageSubCategoryId
        this.datetime = datetime
        this.createdDatetime = createdDatetime
        this.updateDatetime = updateDatetime
        this.amount = amount
        resetChangedOnNotNull()
    }
}
