/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import java.time.LocalDateTime

import net.matsudamper.money.db.schema.tables.JMoneyUsagePresets

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JMoneyUsagePresetsRecord() : UpdatableRecordImpl<JMoneyUsagePresetsRecord>(JMoneyUsagePresets.MONEY_USAGE_PRESETS) {

    open var moneyUsagePresetId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var userId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var name: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var moneyUsageSubCategoryId: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var orderNumber: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var createdDatetime: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var updateDatetime: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var amount: Int?
        set(value): Unit = set(7, value)
        get(): Int? = get(7) as Int?

    open var description: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised JMoneyUsagePresetsRecord
     */
    constructor(moneyUsagePresetId: Int? = null, userId: Int? = null, name: String? = null, moneyUsageSubCategoryId: Int? = null, orderNumber: Int? = null, createdDatetime: LocalDateTime? = null, updateDatetime: LocalDateTime? = null, amount: Int? = null, description: String? = null): this() {
        this.moneyUsagePresetId = moneyUsagePresetId
        this.userId = userId
        this.name = name
        this.moneyUsageSubCategoryId = moneyUsageSubCategoryId
        this.orderNumber = orderNumber
        this.createdDatetime = createdDatetime
        this.updateDatetime = updateDatetime
        this.amount = amount
        this.description = description
        resetTouchedOnNotNull()
    }
}
