/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import net.matsudamper.money.db.schema.tables.JMoneyUsageImagesRelation

import org.jooq.Record3
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JMoneyUsageImagesRelationRecord() : UpdatableRecordImpl<JMoneyUsageImagesRelationRecord>(JMoneyUsageImagesRelation.MONEY_USAGE_IMAGES_RELATION) {

    open var userId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var moneyUsageId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var userImageId: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var imageOrder: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record3<Int?, Int?, Int?> = super.key() as Record3<Int?, Int?, Int?>

    /**
     * Create a detached, initialised JMoneyUsageImagesRelationRecord
     */
    constructor(userId: Int? = null, moneyUsageId: Int? = null, userImageId: Int? = null, imageOrder: Int? = null): this() {
        this.userId = userId
        this.moneyUsageId = moneyUsageId
        this.userImageId = userImageId
        this.imageOrder = imageOrder
        resetTouchedOnNotNull()
    }
}
