/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import net.matsudamper.money.db.schema.tables.JUserSetting

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JUserSettingRecord() : UpdatableRecordImpl<JUserSettingRecord>(JUserSetting.USER_SETTING) {

    open var userId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var timezoneOffsetMinutes: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised JUserSettingRecord
     */
    constructor(userId: Int? = null, timezoneOffsetMinutes: Int? = null): this() {
        this.userId = userId
        this.timezoneOffsetMinutes = timezoneOffsetMinutes
        resetTouchedOnNotNull()
    }
}
