/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import java.time.LocalDateTime

import net.matsudamper.money.db.schema.tables.JUserImages

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JUserImagesRecord() : UpdatableRecordImpl<JUserImagesRecord>(JUserImages.USER_IMAGES) {

    open var userImageId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var userId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var displayId: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var imagePath: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var contentType: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var createdDatetime: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var uploaded: Boolean?
        set(value): Unit = set(6, value)
        get(): Boolean? = get(6) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised JUserImagesRecord
     */
    constructor(userImageId: Int? = null, userId: Int? = null, displayId: String? = null, imagePath: String? = null, contentType: String? = null, createdDatetime: LocalDateTime? = null, uploaded: Boolean? = null): this() {
        this.userImageId = userImageId
        this.userId = userId
        this.displayId = displayId
        this.imagePath = imagePath
        this.contentType = contentType
        this.createdDatetime = createdDatetime
        this.uploaded = uploaded
        resetTouchedOnNotNull()
    }
}
