/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import java.time.LocalDateTime

import net.matsudamper.money.db.schema.tables.JUserMails

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JUserMailsRecord() : UpdatableRecordImpl<JUserMailsRecord>(JUserMails.USER_MAILS) {

    open var userMailId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var userId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var plain: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var html: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var datetime: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    open var createdDatetime: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var fromMail: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var subject: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised JUserMailsRecord
     */
    constructor(userMailId: Int? = null, userId: Int? = null, plain: String? = null, html: String? = null, datetime: LocalDateTime? = null, createdDatetime: LocalDateTime? = null, fromMail: String? = null, subject: String? = null): this() {
        this.userMailId = userMailId
        this.userId = userId
        this.plain = plain
        this.html = html
        this.datetime = datetime
        this.createdDatetime = createdDatetime
        this.fromMail = fromMail
        this.subject = subject
        resetTouchedOnNotNull()
    }
}
