/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import net.matsudamper.money.db.schema.tables.JUserMailAiParseResults

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JUserMailAiParseResultsRecord() : UpdatableRecordImpl<JUserMailAiParseResultsRecord>(JUserMailAiParseResults.USER_MAIL_AI_PARSE_RESULTS) {

    open var userMailId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var userId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var status: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var resultJson: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var errorMessage: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var updateDatetime: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised JUserMailAiParseResultsRecord
     */
    constructor(userMailId: Int? = null, userId: Int? = null, status: String? = null, resultJson: String? = null, errorMessage: String? = null, updateDatetime: LocalDateTime? = null): this() {
        this.userMailId = userMailId
        this.userId = userId
        this.status = status
        this.resultJson = resultJson
        this.errorMessage = errorMessage
        this.updateDatetime = updateDatetime
        resetTouchedOnNotNull()
    }
}
