/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import net.matsudamper.money.db.schema.tables.JUserGeminiSettings

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JUserGeminiSettingsRecord() : UpdatableRecordImpl<JUserGeminiSettingsRecord>(JUserGeminiSettings.USER_GEMINI_SETTINGS) {

    open var userId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var encryptedApiKey: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised JUserGeminiSettingsRecord
     */
    constructor(userId: Int? = null, encryptedApiKey: String? = null): this() {
        this.userId = userId
        this.encryptedApiKey = encryptedApiKey
        resetTouchedOnNotNull()
    }
}
