/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import java.time.LocalDateTime

import net.matsudamper.money.db.schema.tables.JUserSessions

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record4
import org.jooq.Row4
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JUserSessionsRecord() : UpdatableRecordImpl<JUserSessionsRecord>(JUserSessions.USER_SESSIONS), Record4<String?, Int?, LocalDateTime?, LocalDateTime?> {

    open var sessionId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var userId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var createdDate: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var expireDatetime: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row4<String?, Int?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row4<String?, Int?, LocalDateTime?, LocalDateTime?>
    override fun valuesRow(): Row4<String?, Int?, LocalDateTime?, LocalDateTime?> = super.valuesRow() as Row4<String?, Int?, LocalDateTime?, LocalDateTime?>
    override fun field1(): Field<String?> = JUserSessions.USER_SESSIONS.SESSION_ID
    override fun field2(): Field<Int?> = JUserSessions.USER_SESSIONS.USER_ID
    override fun field3(): Field<LocalDateTime?> = JUserSessions.USER_SESSIONS.CREATED_DATE
    override fun field4(): Field<LocalDateTime?> = JUserSessions.USER_SESSIONS.EXPIRE_DATETIME
    override fun component1(): String? = sessionId
    override fun component2(): Int? = userId
    override fun component3(): LocalDateTime? = createdDate
    override fun component4(): LocalDateTime? = expireDatetime
    override fun value1(): String? = sessionId
    override fun value2(): Int? = userId
    override fun value3(): LocalDateTime? = createdDate
    override fun value4(): LocalDateTime? = expireDatetime

    override fun value1(value: String?): JUserSessionsRecord {
        set(0, value)
        return this
    }

    override fun value2(value: Int?): JUserSessionsRecord {
        set(1, value)
        return this
    }

    override fun value3(value: LocalDateTime?): JUserSessionsRecord {
        set(2, value)
        return this
    }

    override fun value4(value: LocalDateTime?): JUserSessionsRecord {
        set(3, value)
        return this
    }

    override fun values(value1: String?, value2: Int?, value3: LocalDateTime?, value4: LocalDateTime?): JUserSessionsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        return this
    }

    /**
     * Create a detached, initialised JUserSessionsRecord
     */
    constructor(sessionId: String? = null, userId: Int? = null, createdDate: LocalDateTime? = null, expireDatetime: LocalDateTime? = null): this() {
        this.sessionId = sessionId
        this.userId = userId
        this.createdDate = createdDate
        this.expireDatetime = expireDatetime
        resetChangedOnNotNull()
    }
}
