/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import java.time.LocalDateTime

import net.matsudamper.money.db.schema.tables.JUserPasswords

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JUserPasswordsRecord() : UpdatableRecordImpl<JUserPasswordsRecord>(JUserPasswords.USER_PASSWORDS) {

    open var userId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var passwordHash: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var createdDatetime: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var updateDatetime: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised JUserPasswordsRecord
     */
    constructor(userId: Int? = null, passwordHash: String? = null, createdDatetime: LocalDateTime? = null, updateDatetime: LocalDateTime? = null): this() {
        this.userId = userId
        this.passwordHash = passwordHash
        this.createdDatetime = createdDatetime
        this.updateDatetime = updateDatetime
        resetTouchedOnNotNull()
    }
}
