/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import java.time.LocalDateTime

import net.matsudamper.money.db.schema.tables.JUserImages

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JUserImagesRecord() : UpdatableRecordImpl<JUserImagesRecord>(JUserImages.USER_IMAGES) {

    open var imageId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var userId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var displayId: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var imagePath: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var createdDatetime: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised JUserImagesRecord
     */
    constructor(imageId: Int? = null, userId: Int? = null, displayId: String? = null, imagePath: String? = null, createdDatetime: LocalDateTime? = null): this() {
        this.imageId = imageId
        this.userId = userId
        this.displayId = displayId
        this.imagePath = imagePath
        this.createdDatetime = createdDatetime
        resetTouchedOnNotNull()
    }
}
