version: "3"

services:
  redis:
    restart: always
    image: redis:latest
    volumes:
      - ./redis:/redis
  money:
    image: ghcr.io/matsudamper/kake-bo:latest
    env_file:
      - .env
    ports:
      - 9060:80
    # environment
    # volumes
