@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.references


import net.matsudamper.money.db.schema.tables.JAdminSessions
import net.matsudamper.money.db.schema.tables.JApiTokens
import net.matsudamper.money.db.schema.tables.JCategoryMailFilterConditionOperatorType
import net.matsudamper.money.db.schema.tables.JCategoryMailFilterConditionType
import net.matsudamper.money.db.schema.tables.JCategoryMailFilterConditions
import net.matsudamper.money.db.schema.tables.JCategoryMailFilterDatasourceType
import net.matsudamper.money.db.schema.tables.JCategoryMailFilters
import net.matsudamper.money.db.schema.tables.JMoneyUsageCategories
import net.matsudamper.money.db.schema.tables.JMoneyUsageSubCategories
import net.matsudamper.money.db.schema.tables.JMoneyUsages
import net.matsudamper.money.db.schema.tables.JMoneyUsagesMailsRelation
import net.matsudamper.money.db.schema.tables.JUserImapSettings
import net.matsudamper.money.db.schema.tables.JUserMails
import net.matsudamper.money.db.schema.tables.JUserPasswordExtendData
import net.matsudamper.money.db.schema.tables.JUserPasswords
import net.matsudamper.money.db.schema.tables.JUserSessions
import net.matsudamper.money.db.schema.tables.JUsers
import net.matsudamper.money.db.schema.tables.JWebAuthAuthenticator



/**
 * The table <code>money.admin_sessions</code>.
 */
val ADMIN_SESSIONS: JAdminSessions = JAdminSessions.ADMIN_SESSIONS

/**
 * The table <code>money.api_tokens</code>.
 */
val API_TOKENS: JApiTokens = JApiTokens.API_TOKENS

/**
 * The table <code>money.category_mail_filter_condition_operator_type</code>.
 */
val CATEGORY_MAIL_FILTER_CONDITION_OPERATOR_TYPE: JCategoryMailFilterConditionOperatorType = JCategoryMailFilterConditionOperatorType.CATEGORY_MAIL_FILTER_CONDITION_OPERATOR_TYPE

/**
 * The table <code>money.category_mail_filter_condition_type</code>.
 */
val CATEGORY_MAIL_FILTER_CONDITION_TYPE: JCategoryMailFilterConditionType = JCategoryMailFilterConditionType.CATEGORY_MAIL_FILTER_CONDITION_TYPE

/**
 * The table <code>money.category_mail_filter_conditions</code>.
 */
val CATEGORY_MAIL_FILTER_CONDITIONS: JCategoryMailFilterConditions = JCategoryMailFilterConditions.CATEGORY_MAIL_FILTER_CONDITIONS

/**
 * The table <code>money.category_mail_filter_datasource_type</code>.
 */
val CATEGORY_MAIL_FILTER_DATASOURCE_TYPE: JCategoryMailFilterDatasourceType = JCategoryMailFilterDatasourceType.CATEGORY_MAIL_FILTER_DATASOURCE_TYPE

/**
 * The table <code>money.category_mail_filters</code>.
 */
val CATEGORY_MAIL_FILTERS: JCategoryMailFilters = JCategoryMailFilters.CATEGORY_MAIL_FILTERS

/**
 * The table <code>money.money_usage_categories</code>.
 */
val MONEY_USAGE_CATEGORIES: JMoneyUsageCategories = JMoneyUsageCategories.MONEY_USAGE_CATEGORIES

/**
 * The table <code>money.money_usage_sub_categories</code>.
 */
val MONEY_USAGE_SUB_CATEGORIES: JMoneyUsageSubCategories = JMoneyUsageSubCategories.MONEY_USAGE_SUB_CATEGORIES

/**
 * The table <code>money.money_usages</code>.
 */
val MONEY_USAGES: JMoneyUsages = JMoneyUsages.MONEY_USAGES

/**
 * The table <code>money.money_usages_mails_relation</code>.
 */
val MONEY_USAGES_MAILS_RELATION: JMoneyUsagesMailsRelation = JMoneyUsagesMailsRelation.MONEY_USAGES_MAILS_RELATION

/**
 * The table <code>money.user_imap_settings</code>.
 */
val USER_IMAP_SETTINGS: JUserImapSettings = JUserImapSettings.USER_IMAP_SETTINGS

/**
 * The table <code>money.user_mails</code>.
 */
val USER_MAILS: JUserMails = JUserMails.USER_MAILS

/**
 * The table <code>money.user_password_extend_data</code>.
 */
val USER_PASSWORD_EXTEND_DATA: JUserPasswordExtendData = JUserPasswordExtendData.USER_PASSWORD_EXTEND_DATA

/**
 * The table <code>money.user_passwords</code>.
 */
val USER_PASSWORDS: JUserPasswords = JUserPasswords.USER_PASSWORDS

/**
 * The table <code>money.user_sessions</code>.
 */
val USER_SESSIONS: JUserSessions = JUserSessions.USER_SESSIONS

/**
 * The table <code>money.users</code>.
 */
val USERS: JUsers = JUsers.USERS

/**
 * The table <code>money.web_auth_authenticator</code>.
 */
val WEB_AUTH_AUTHENTICATOR: JWebAuthAuthenticator = JWebAuthAuthenticator.WEB_AUTH_AUTHENTICATOR
