[versions]
kotlin = "2.0.0"
compose-plugin = "1.6.10"
apollo = "4.0.0-beta.6"
ktor = "3.0.0-beta-2"

[plugins]

[libraries]
ktorServerCore = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktorServerEngine = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktorServerStatusPages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktorServerCors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktorServerDefaultHeaders = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktorServerFowardedHeader = { module = "io.ktor:ktor-server-forwarded-header", version.ref = "ktor" }
ktorServerCompression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
ktorSerializationJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorServerContentNegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktorServerCallLogging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorClientJs = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktorClientLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
