/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.indexes


import net.matsudamper.money.db.schema.tables.JUserSessions
import net.matsudamper.money.db.schema.tables.JUsers

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val USER_SESSIONS_USER_ID: Index = Internal.createIndex(DSL.name("user_id"), JUserSessions.USER_SESSIONS, arrayOf(JUserSessions.USER_SESSIONS.USER_ID), false)
val USERS_USER_NAME: Index = Internal.createIndex(DSL.name("user_name"), JUsers.USERS, arrayOf(JUsers.USERS.USER_NAME), false)
