/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.indexes


import net.matsudamper.money.db.schema.tables.JMoneyUsageCategories
import net.matsudamper.money.db.schema.tables.JMoneyUsageSubCategories
import net.matsudamper.money.db.schema.tables.JMoneyUsages
import net.matsudamper.money.db.schema.tables.JUserMails
import net.matsudamper.money.db.schema.tables.JUserSessions
import net.matsudamper.money.db.schema.tables.JUsers

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val MONEY_USAGES_USER_ID: Index = Internal.createIndex(DSL.name("user_id"), JMoneyUsages.MONEY_USAGES, arrayOf(JMoneyUsages.MONEY_USAGES.USER_ID), false)
val MONEY_USAGE_CATEGORIES_USER_ID: Index = Internal.createIndex(DSL.name("user_id"), JMoneyUsageCategories.MONEY_USAGE_CATEGORIES, arrayOf(JMoneyUsageCategories.MONEY_USAGE_CATEGORIES.USER_ID), false)
val MONEY_USAGE_SUB_CATEGORIES_USER_ID: Index = Internal.createIndex(DSL.name("user_id"), JMoneyUsageSubCategories.MONEY_USAGE_SUB_CATEGORIES, arrayOf(JMoneyUsageSubCategories.MONEY_USAGE_SUB_CATEGORIES.USER_ID), false)
val USER_MAILS_USER_ID: Index = Internal.createIndex(DSL.name("user_id"), JUserMails.USER_MAILS, arrayOf(JUserMails.USER_MAILS.USER_ID), false)
val USER_SESSIONS_USER_ID: Index = Internal.createIndex(DSL.name("user_id"), JUserSessions.USER_SESSIONS, arrayOf(JUserSessions.USER_SESSIONS.USER_ID), false)
val MONEY_USAGES_USER_INDEX: Index = Internal.createIndex(DSL.name("user_index"), JMoneyUsages.MONEY_USAGES, arrayOf(JMoneyUsages.MONEY_USAGES.MONEY_USAGE_ID, JMoneyUsages.MONEY_USAGES.USER_ID), false)
val MONEY_USAGE_CATEGORIES_USER_INDEX: Index = Internal.createIndex(DSL.name("user_index"), JMoneyUsageCategories.MONEY_USAGE_CATEGORIES, arrayOf(JMoneyUsageCategories.MONEY_USAGE_CATEGORIES.MONEY_USAGE_CATEGORY_ID, JMoneyUsageCategories.MONEY_USAGE_CATEGORIES.USER_ID), false)
val MONEY_USAGE_SUB_CATEGORIES_USER_INDEX: Index = Internal.createIndex(DSL.name("user_index"), JMoneyUsageSubCategories.MONEY_USAGE_SUB_CATEGORIES, arrayOf(JMoneyUsageSubCategories.MONEY_USAGE_SUB_CATEGORIES.MONEY_USAGE_SUB_CATEGORY_ID, JMoneyUsageSubCategories.MONEY_USAGE_SUB_CATEGORIES.USER_ID), false)
val USER_MAILS_USER_INDEX: Index = Internal.createIndex(DSL.name("user_index"), JUserMails.USER_MAILS, arrayOf(JUserMails.USER_MAILS.USER_MAIL_ID, JUserMails.USER_MAILS.USER_ID), false)
val USERS_USER_NAME: Index = Internal.createIndex(DSL.name("user_name"), JUsers.USERS, arrayOf(JUsers.USERS.USER_NAME), false)
