/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import java.time.LocalDateTime
import java.util.function.Function

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.keys.KEY_ADMIN_SESSIONS_PRIMARY
import net.matsudamper.money.db.schema.tables.records.JAdminSessionsRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JAdminSessions(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, JAdminSessionsRecord>?,
    aliased: Table<JAdminSessionsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<JAdminSessionsRecord>(
    alias,
    JMoney.MONEY,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>money.admin_sessions</code>
         */
        val ADMIN_SESSIONS: JAdminSessions = JAdminSessions()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JAdminSessionsRecord> = JAdminSessionsRecord::class.java

    /**
     * The column <code>money.admin_sessions.session_id</code>.
     */
    val SESSION_ID: TableField<JAdminSessionsRecord, String?> = createField(DSL.name("session_id"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>money.admin_sessions.created_date</code>.
     */
    val CREATED_DATE: TableField<JAdminSessionsRecord, LocalDateTime?> = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>money.admin_sessions.expire_datetime</code>.
     */
    val EXPIRE_DATETIME: TableField<JAdminSessionsRecord, LocalDateTime?> = createField(DSL.name("expire_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<JAdminSessionsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<JAdminSessionsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>money.admin_sessions</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.admin_sessions</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.admin_sessions</code> table reference
     */
    constructor(): this(DSL.name("admin_sessions"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, JAdminSessionsRecord>): this(Internal.createPathAlias(child, key), child, key, ADMIN_SESSIONS, null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getPrimaryKey(): UniqueKey<JAdminSessionsRecord> = KEY_ADMIN_SESSIONS_PRIMARY
    override fun `as`(alias: String): JAdminSessions = JAdminSessions(DSL.name(alias), this)
    override fun `as`(alias: Name): JAdminSessions = JAdminSessions(alias, this)
    override fun `as`(alias: Table<*>): JAdminSessions = JAdminSessions(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JAdminSessions = JAdminSessions(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JAdminSessions = JAdminSessions(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JAdminSessions = JAdminSessions(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row3<String?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row3<String?, LocalDateTime?, LocalDateTime?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
