/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import java.time.LocalDateTime
import java.util.function.Function

import kotlin.collections.List

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.indexes.CATEGORY_MAIL_FILTERS_USER_CATEGORY_MAIL_FILTER_ID
import net.matsudamper.money.db.schema.keys.KEY_CATEGORY_MAIL_FILTERS_PRIMARY
import net.matsudamper.money.db.schema.tables.records.JCategoryMailFiltersRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row8
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JCategoryMailFilters(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, JCategoryMailFiltersRecord>?,
    aliased: Table<JCategoryMailFiltersRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<JCategoryMailFiltersRecord>(
    alias,
    JMoney.MONEY,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>money.category_mail_filters</code>
         */
        val CATEGORY_MAIL_FILTERS: JCategoryMailFilters = JCategoryMailFilters()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JCategoryMailFiltersRecord> = JCategoryMailFiltersRecord::class.java

    /**
     * The column
     * <code>money.category_mail_filters.category_mail_filter_id</code>.
     */
    val CATEGORY_MAIL_FILTER_ID: TableField<JCategoryMailFiltersRecord, Int?> = createField(DSL.name("category_mail_filter_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>money.category_mail_filters.user_id</code>.
     */
    val USER_ID: TableField<JCategoryMailFiltersRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.category_mail_filters.title</code>.
     */
    val TITLE: TableField<JCategoryMailFiltersRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(500).nullable(false), this, "")

    /**
     * The column
     * <code>money.category_mail_filters.money_usage_sub_category_id</code>.
     */
    val MONEY_USAGE_SUB_CATEGORY_ID: TableField<JCategoryMailFiltersRecord, Int?> = createField(DSL.name("money_usage_sub_category_id"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "")

    /**
     * The column
     * <code>money.category_mail_filters.category_mail_filter_condition_operator_type_id</code>.
     */
    val CATEGORY_MAIL_FILTER_CONDITION_OPERATOR_TYPE_ID: TableField<JCategoryMailFiltersRecord, Int?> = createField(DSL.name("category_mail_filter_condition_operator_type_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.category_mail_filters.created_datetime</code>.
     */
    val CREATED_DATETIME: TableField<JCategoryMailFiltersRecord, LocalDateTime?> = createField(DSL.name("created_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>money.category_mail_filters.update_datetime</code>.
     */
    val UPDATE_DATETIME: TableField<JCategoryMailFiltersRecord, LocalDateTime?> = createField(DSL.name("update_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>money.category_mail_filters.order_number</code>.
     */
    val ORDER_NUMBER: TableField<JCategoryMailFiltersRecord, Int?> = createField(DSL.name("order_number"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<JCategoryMailFiltersRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<JCategoryMailFiltersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>money.category_mail_filters</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.category_mail_filters</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.category_mail_filters</code> table reference
     */
    constructor(): this(DSL.name("category_mail_filters"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, JCategoryMailFiltersRecord>): this(Internal.createPathAlias(child, key), child, key, CATEGORY_MAIL_FILTERS, null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getIndexes(): List<Index> = listOf(CATEGORY_MAIL_FILTERS_USER_CATEGORY_MAIL_FILTER_ID)
    override fun getIdentity(): Identity<JCategoryMailFiltersRecord, Int?> = super.getIdentity() as Identity<JCategoryMailFiltersRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<JCategoryMailFiltersRecord> = KEY_CATEGORY_MAIL_FILTERS_PRIMARY
    override fun `as`(alias: String): JCategoryMailFilters = JCategoryMailFilters(DSL.name(alias), this)
    override fun `as`(alias: Name): JCategoryMailFilters = JCategoryMailFilters(alias, this)
    override fun `as`(alias: Table<*>): JCategoryMailFilters = JCategoryMailFilters(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JCategoryMailFilters = JCategoryMailFilters(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JCategoryMailFilters = JCategoryMailFilters(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JCategoryMailFilters = JCategoryMailFilters(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row8<Int?, Int?, String?, Int?, Int?, LocalDateTime?, LocalDateTime?, Int?> = super.fieldsRow() as Row8<Int?, Int?, String?, Int?, Int?, LocalDateTime?, LocalDateTime?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, Int?, String?, Int?, Int?, LocalDateTime?, LocalDateTime?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, Int?, String?, Int?, Int?, LocalDateTime?, LocalDateTime?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
