/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import java.time.LocalDateTime
import java.util.function.Function

import kotlin.collections.List

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.indexes.CATEGORY_MAIL_FILTER_CONDITION_GROUPS_USER_CATEGORY_MAIL_FILTER_CONDITION_GROUP_ID
import net.matsudamper.money.db.schema.indexes.CATEGORY_MAIL_FILTER_CONDITION_GROUPS_USER_CATEGORY_MAIL_FILTER_ID
import net.matsudamper.money.db.schema.keys.KEY_CATEGORY_MAIL_FILTER_CONDITION_GROUPS_PRIMARY
import net.matsudamper.money.db.schema.tables.records.JCategoryMailFilterConditionGroupsRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row7
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JCategoryMailFilterConditionGroups(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, JCategoryMailFilterConditionGroupsRecord>?,
    aliased: Table<JCategoryMailFilterConditionGroupsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<JCategoryMailFilterConditionGroupsRecord>(
    alias,
    JMoney.MONEY,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>money.category_mail_filter_condition_groups</code>
         */
        val CATEGORY_MAIL_FILTER_CONDITION_GROUPS: JCategoryMailFilterConditionGroups = JCategoryMailFilterConditionGroups()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JCategoryMailFilterConditionGroupsRecord> = JCategoryMailFilterConditionGroupsRecord::class.java

    /**
     * The column
     * <code>money.category_mail_filter_condition_groups.category_mail_filter_condition_group_id</code>.
     */
    val CATEGORY_MAIL_FILTER_CONDITION_GROUP_ID: TableField<JCategoryMailFilterConditionGroupsRecord, Int?> = createField(DSL.name("category_mail_filter_condition_group_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column
     * <code>money.category_mail_filter_condition_groups.category_mail_filter_id</code>.
     */
    val CATEGORY_MAIL_FILTER_ID: TableField<JCategoryMailFilterConditionGroupsRecord, Int?> = createField(DSL.name("category_mail_filter_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column
     * <code>money.category_mail_filter_condition_groups.user_id</code>.
     */
    val USER_ID: TableField<JCategoryMailFilterConditionGroupsRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column
     * <code>money.category_mail_filter_condition_groups.title</code>.
     */
    val TITLE: TableField<JCategoryMailFilterConditionGroupsRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(500).nullable(false), this, "")

    /**
     * The column
     * <code>money.category_mail_filter_condition_groups.category_mail_filter_condition_operator_type_id</code>.
     */
    val CATEGORY_MAIL_FILTER_CONDITION_OPERATOR_TYPE_ID: TableField<JCategoryMailFilterConditionGroupsRecord, Int?> = createField(DSL.name("category_mail_filter_condition_operator_type_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column
     * <code>money.category_mail_filter_condition_groups.created_datetime</code>.
     */
    val CREATED_DATETIME: TableField<JCategoryMailFilterConditionGroupsRecord, LocalDateTime?> = createField(DSL.name("created_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column
     * <code>money.category_mail_filter_condition_groups.update_datetime</code>.
     */
    val UPDATE_DATETIME: TableField<JCategoryMailFilterConditionGroupsRecord, LocalDateTime?> = createField(DSL.name("update_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<JCategoryMailFilterConditionGroupsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<JCategoryMailFilterConditionGroupsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased
     * <code>money.category_mail_filter_condition_groups</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased
     * <code>money.category_mail_filter_condition_groups</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.category_mail_filter_condition_groups</code> table
     * reference
     */
    constructor(): this(DSL.name("category_mail_filter_condition_groups"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, JCategoryMailFilterConditionGroupsRecord>): this(Internal.createPathAlias(child, key), child, key, CATEGORY_MAIL_FILTER_CONDITION_GROUPS, null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getIndexes(): List<Index> = listOf(CATEGORY_MAIL_FILTER_CONDITION_GROUPS_USER_CATEGORY_MAIL_FILTER_CONDITION_GROUP_ID, CATEGORY_MAIL_FILTER_CONDITION_GROUPS_USER_CATEGORY_MAIL_FILTER_ID)
    override fun getIdentity(): Identity<JCategoryMailFilterConditionGroupsRecord, Int?> = super.getIdentity() as Identity<JCategoryMailFilterConditionGroupsRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<JCategoryMailFilterConditionGroupsRecord> = KEY_CATEGORY_MAIL_FILTER_CONDITION_GROUPS_PRIMARY
    override fun `as`(alias: String): JCategoryMailFilterConditionGroups = JCategoryMailFilterConditionGroups(DSL.name(alias), this)
    override fun `as`(alias: Name): JCategoryMailFilterConditionGroups = JCategoryMailFilterConditionGroups(alias, this)
    override fun `as`(alias: Table<*>): JCategoryMailFilterConditionGroups = JCategoryMailFilterConditionGroups(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JCategoryMailFilterConditionGroups = JCategoryMailFilterConditionGroups(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JCategoryMailFilterConditionGroups = JCategoryMailFilterConditionGroups(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JCategoryMailFilterConditionGroups = JCategoryMailFilterConditionGroups(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row7<Int?, Int?, Int?, String?, Int?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row7<Int?, Int?, Int?, String?, Int?, LocalDateTime?, LocalDateTime?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, Int?, Int?, String?, Int?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, Int?, Int?, String?, Int?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
