/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import java.time.LocalDateTime
import java.util.function.Function

import kotlin.collections.List

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.indexes.MONEY_USAGES_MAILS_RELATION_MONEY_USAGE_ID
import net.matsudamper.money.db.schema.indexes.MONEY_USAGES_MAILS_RELATION_USER_ID
import net.matsudamper.money.db.schema.indexes.MONEY_USAGES_MAILS_RELATION_USER_MAIL_ID
import net.matsudamper.money.db.schema.keys.KEY_MONEY_USAGES_MAILS_RELATION_PRIMARY
import net.matsudamper.money.db.schema.tables.records.JMoneyUsagesMailsRelationRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JMoneyUsagesMailsRelation(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, JMoneyUsagesMailsRelationRecord>?,
    aliased: Table<JMoneyUsagesMailsRelationRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<JMoneyUsagesMailsRelationRecord>(
    alias,
    JMoney.MONEY,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>money.money_usages_mails_relation</code>
         */
        val MONEY_USAGES_MAILS_RELATION: JMoneyUsagesMailsRelation = JMoneyUsagesMailsRelation()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JMoneyUsagesMailsRelationRecord> = JMoneyUsagesMailsRelationRecord::class.java

    /**
     * The column <code>money.money_usages_mails_relation.user_id</code>.
     */
    val USER_ID: TableField<JMoneyUsagesMailsRelationRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.money_usages_mails_relation.money_usage_id</code>.
     */
    val MONEY_USAGE_ID: TableField<JMoneyUsagesMailsRelationRecord, Int?> = createField(DSL.name("money_usage_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.money_usages_mails_relation.user_mail_id</code>.
     */
    val USER_MAIL_ID: TableField<JMoneyUsagesMailsRelationRecord, Int?> = createField(DSL.name("user_mail_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column
     * <code>money.money_usages_mails_relation.created_datetime</code>.
     */
    val CREATED_DATETIME: TableField<JMoneyUsagesMailsRelationRecord, LocalDateTime?> = createField(DSL.name("created_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<JMoneyUsagesMailsRelationRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<JMoneyUsagesMailsRelationRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>money.money_usages_mails_relation</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.money_usages_mails_relation</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.money_usages_mails_relation</code> table reference
     */
    constructor(): this(DSL.name("money_usages_mails_relation"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, JMoneyUsagesMailsRelationRecord>): this(Internal.createPathAlias(child, key), child, key, MONEY_USAGES_MAILS_RELATION, null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getIndexes(): List<Index> = listOf(MONEY_USAGES_MAILS_RELATION_MONEY_USAGE_ID, MONEY_USAGES_MAILS_RELATION_USER_ID, MONEY_USAGES_MAILS_RELATION_USER_MAIL_ID)
    override fun getPrimaryKey(): UniqueKey<JMoneyUsagesMailsRelationRecord> = KEY_MONEY_USAGES_MAILS_RELATION_PRIMARY
    override fun `as`(alias: String): JMoneyUsagesMailsRelation = JMoneyUsagesMailsRelation(DSL.name(alias), this)
    override fun `as`(alias: Name): JMoneyUsagesMailsRelation = JMoneyUsagesMailsRelation(alias, this)
    override fun `as`(alias: Table<*>): JMoneyUsagesMailsRelation = JMoneyUsagesMailsRelation(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JMoneyUsagesMailsRelation = JMoneyUsagesMailsRelation(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JMoneyUsagesMailsRelation = JMoneyUsagesMailsRelation(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JMoneyUsagesMailsRelation = JMoneyUsagesMailsRelation(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Int?, Int?, Int?, LocalDateTime?> = super.fieldsRow() as Row4<Int?, Int?, Int?, LocalDateTime?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, Int?, Int?, LocalDateTime?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, Int?, Int?, LocalDateTime?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
