/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import java.time.LocalDateTime
import java.util.function.Function

import kotlin.collections.List

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.indexes.MONEY_USAGE_SUB_CATEGORIES_USER_ID
import net.matsudamper.money.db.schema.indexes.MONEY_USAGE_SUB_CATEGORIES_USER_INDEX
import net.matsudamper.money.db.schema.keys.KEY_MONEY_USAGE_SUB_CATEGORIES_PRIMARY
import net.matsudamper.money.db.schema.tables.records.JMoneyUsageSubCategoriesRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JMoneyUsageSubCategories(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, JMoneyUsageSubCategoriesRecord>?,
    aliased: Table<JMoneyUsageSubCategoriesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<JMoneyUsageSubCategoriesRecord>(
    alias,
    JMoney.MONEY,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>money.money_usage_sub_categories</code>
         */
        val MONEY_USAGE_SUB_CATEGORIES: JMoneyUsageSubCategories = JMoneyUsageSubCategories()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JMoneyUsageSubCategoriesRecord> = JMoneyUsageSubCategoriesRecord::class.java

    /**
     * The column
     * <code>money.money_usage_sub_categories.money_usage_sub_category_id</code>.
     */
    val MONEY_USAGE_SUB_CATEGORY_ID: TableField<JMoneyUsageSubCategoriesRecord, Int?> = createField(DSL.name("money_usage_sub_category_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>money.money_usage_sub_categories.user_id</code>.
     */
    val USER_ID: TableField<JMoneyUsageSubCategoriesRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column
     * <code>money.money_usage_sub_categories.money_usage_category_id</code>.
     */
    val MONEY_USAGE_CATEGORY_ID: TableField<JMoneyUsageSubCategoriesRecord, Int?> = createField(DSL.name("money_usage_category_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.money_usage_sub_categories.name</code>.
     */
    val NAME: TableField<JMoneyUsageSubCategoriesRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(500).nullable(false), this, "")

    /**
     * The column
     * <code>money.money_usage_sub_categories.created_datetime</code>.
     */
    val CREATED_DATETIME: TableField<JMoneyUsageSubCategoriesRecord, LocalDateTime?> = createField(DSL.name("created_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>money.money_usage_sub_categories.update_datetime</code>.
     */
    val UPDATE_DATETIME: TableField<JMoneyUsageSubCategoriesRecord, LocalDateTime?> = createField(DSL.name("update_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<JMoneyUsageSubCategoriesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<JMoneyUsageSubCategoriesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>money.money_usage_sub_categories</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.money_usage_sub_categories</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.money_usage_sub_categories</code> table reference
     */
    constructor(): this(DSL.name("money_usage_sub_categories"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, JMoneyUsageSubCategoriesRecord>): this(Internal.createPathAlias(child, key), child, key, MONEY_USAGE_SUB_CATEGORIES, null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getIndexes(): List<Index> = listOf(MONEY_USAGE_SUB_CATEGORIES_USER_ID, MONEY_USAGE_SUB_CATEGORIES_USER_INDEX)
    override fun getIdentity(): Identity<JMoneyUsageSubCategoriesRecord, Int?> = super.getIdentity() as Identity<JMoneyUsageSubCategoriesRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<JMoneyUsageSubCategoriesRecord> = KEY_MONEY_USAGE_SUB_CATEGORIES_PRIMARY
    override fun `as`(alias: String): JMoneyUsageSubCategories = JMoneyUsageSubCategories(DSL.name(alias), this)
    override fun `as`(alias: Name): JMoneyUsageSubCategories = JMoneyUsageSubCategories(alias, this)
    override fun `as`(alias: Table<*>): JMoneyUsageSubCategories = JMoneyUsageSubCategories(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JMoneyUsageSubCategories = JMoneyUsageSubCategories(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JMoneyUsageSubCategories = JMoneyUsageSubCategories(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JMoneyUsageSubCategories = JMoneyUsageSubCategories(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row6<Int?, Int?, Int?, String?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row6<Int?, Int?, Int?, String?, LocalDateTime?, LocalDateTime?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, Int?, Int?, String?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, Int?, Int?, String?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
