/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import java.time.LocalDateTime
import java.util.function.Function

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.keys.KEY_USER_PASSWORD_EXTEND_DATA_PRIMARY
import net.matsudamper.money.db.schema.tables.records.JUserPasswordExtendDataRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row7
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JUserPasswordExtendData(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, JUserPasswordExtendDataRecord>?,
    aliased: Table<JUserPasswordExtendDataRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<JUserPasswordExtendDataRecord>(
    alias,
    JMoney.MONEY,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>money.user_password_extend_data</code>
         */
        val USER_PASSWORD_EXTEND_DATA: JUserPasswordExtendData = JUserPasswordExtendData()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JUserPasswordExtendDataRecord> = JUserPasswordExtendDataRecord::class.java

    /**
     * The column <code>money.user_password_extend_data.user_id</code>.
     */
    val USER_ID: TableField<JUserPasswordExtendDataRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.user_password_extend_data.salt</code>.
     */
    val SALT: TableField<JUserPasswordExtendDataRecord, ByteArray?> = createField(DSL.name("salt"), SQLDataType.BINARY(32).nullable(false), this, "")

    /**
     * The column <code>money.user_password_extend_data.iteration_count</code>.
     */
    val ITERATION_COUNT: TableField<JUserPasswordExtendDataRecord, Int?> = createField(DSL.name("iteration_count"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.user_password_extend_data.algorithm</code>.
     */
    val ALGORITHM: TableField<JUserPasswordExtendDataRecord, String?> = createField(DSL.name("algorithm"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>money.user_password_extend_data.key_length</code>.
     */
    val KEY_LENGTH: TableField<JUserPasswordExtendDataRecord, Int?> = createField(DSL.name("key_length"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.user_password_extend_data.created_datetime</code>.
     */
    val CREATED_DATETIME: TableField<JUserPasswordExtendDataRecord, LocalDateTime?> = createField(DSL.name("created_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>money.user_password_extend_data.update_datetime</code>.
     */
    val UPDATE_DATETIME: TableField<JUserPasswordExtendDataRecord, LocalDateTime?> = createField(DSL.name("update_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<JUserPasswordExtendDataRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<JUserPasswordExtendDataRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>money.user_password_extend_data</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.user_password_extend_data</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.user_password_extend_data</code> table reference
     */
    constructor(): this(DSL.name("user_password_extend_data"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, JUserPasswordExtendDataRecord>): this(Internal.createPathAlias(child, key), child, key, USER_PASSWORD_EXTEND_DATA, null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getPrimaryKey(): UniqueKey<JUserPasswordExtendDataRecord> = KEY_USER_PASSWORD_EXTEND_DATA_PRIMARY
    override fun `as`(alias: String): JUserPasswordExtendData = JUserPasswordExtendData(DSL.name(alias), this)
    override fun `as`(alias: Name): JUserPasswordExtendData = JUserPasswordExtendData(alias, this)
    override fun `as`(alias: Table<*>): JUserPasswordExtendData = JUserPasswordExtendData(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JUserPasswordExtendData = JUserPasswordExtendData(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JUserPasswordExtendData = JUserPasswordExtendData(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JUserPasswordExtendData = JUserPasswordExtendData(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row7<Int?, ByteArray?, Int?, String?, Int?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row7<Int?, ByteArray?, Int?, String?, Int?, LocalDateTime?, LocalDateTime?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, ByteArray?, Int?, String?, Int?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, ByteArray?, Int?, String?, Int?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
