/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import java.time.LocalDateTime
import java.util.function.Function

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.keys.KEY_USER_PASSWORDS_PRIMARY
import net.matsudamper.money.db.schema.tables.records.JUserPasswordsRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JUserPasswords(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, JUserPasswordsRecord>?,
    aliased: Table<JUserPasswordsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<JUserPasswordsRecord>(
    alias,
    JMoney.MONEY,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>money.user_passwords</code>
         */
        val USER_PASSWORDS: JUserPasswords = JUserPasswords()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JUserPasswordsRecord> = JUserPasswordsRecord::class.java

    /**
     * The column <code>money.user_passwords.user_id</code>.
     */
    val USER_ID: TableField<JUserPasswordsRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.user_passwords.password_hash</code>.
     */
    val PASSWORD_HASH: TableField<JUserPasswordsRecord, String?> = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(512).nullable(false), this, "")

    /**
     * The column <code>money.user_passwords.created_datetime</code>.
     */
    val CREATED_DATETIME: TableField<JUserPasswordsRecord, LocalDateTime?> = createField(DSL.name("created_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>money.user_passwords.update_datetime</code>.
     */
    val UPDATE_DATETIME: TableField<JUserPasswordsRecord, LocalDateTime?> = createField(DSL.name("update_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<JUserPasswordsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<JUserPasswordsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>money.user_passwords</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.user_passwords</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.user_passwords</code> table reference
     */
    constructor(): this(DSL.name("user_passwords"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, JUserPasswordsRecord>): this(Internal.createPathAlias(child, key), child, key, USER_PASSWORDS, null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getPrimaryKey(): UniqueKey<JUserPasswordsRecord> = KEY_USER_PASSWORDS_PRIMARY
    override fun `as`(alias: String): JUserPasswords = JUserPasswords(DSL.name(alias), this)
    override fun `as`(alias: Name): JUserPasswords = JUserPasswords(alias, this)
    override fun `as`(alias: Table<*>): JUserPasswords = JUserPasswords(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JUserPasswords = JUserPasswords(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JUserPasswords = JUserPasswords(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JUserPasswords = JUserPasswords(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Int?, String?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row4<Int?, String?, LocalDateTime?, LocalDateTime?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, String?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, String?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
