/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables


import java.time.LocalDateTime
import java.util.function.Function

import kotlin.collections.List

import net.matsudamper.money.db.schema.JMoney
import net.matsudamper.money.db.schema.indexes.USER_SESSIONS_USER_ID
import net.matsudamper.money.db.schema.keys.KEY_USER_SESSIONS_PRIMARY
import net.matsudamper.money.db.schema.tables.records.JUserSessionsRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JUserSessions(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, JUserSessionsRecord>?,
    aliased: Table<JUserSessionsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<JUserSessionsRecord>(
    alias,
    JMoney.MONEY,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>money.user_sessions</code>
         */
        val USER_SESSIONS: JUserSessions = JUserSessions()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JUserSessionsRecord> = JUserSessionsRecord::class.java

    /**
     * The column <code>money.user_sessions.session_id</code>.
     */
    val SESSION_ID: TableField<JUserSessionsRecord, String?> = createField(DSL.name("session_id"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>money.user_sessions.user_id</code>.
     */
    val USER_ID: TableField<JUserSessionsRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>money.user_sessions.created_date</code>.
     */
    val CREATED_DATE: TableField<JUserSessionsRecord, LocalDateTime?> = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>money.user_sessions.expire_datetime</code>.
     */
    val EXPIRE_DATETIME: TableField<JUserSessionsRecord, LocalDateTime?> = createField(DSL.name("expire_datetime"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<JUserSessionsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<JUserSessionsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>money.user_sessions</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>money.user_sessions</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>money.user_sessions</code> table reference
     */
    constructor(): this(DSL.name("user_sessions"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, JUserSessionsRecord>): this(Internal.createPathAlias(child, key), child, key, USER_SESSIONS, null)
    override fun getSchema(): Schema? = if (aliased()) null else JMoney.MONEY
    override fun getIndexes(): List<Index> = listOf(USER_SESSIONS_USER_ID)
    override fun getPrimaryKey(): UniqueKey<JUserSessionsRecord> = KEY_USER_SESSIONS_PRIMARY
    override fun `as`(alias: String): JUserSessions = JUserSessions(DSL.name(alias), this)
    override fun `as`(alias: Name): JUserSessions = JUserSessions(alias, this)
    override fun `as`(alias: Table<*>): JUserSessions = JUserSessions(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JUserSessions = JUserSessions(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JUserSessions = JUserSessions(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JUserSessions = JUserSessions(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<String?, Int?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row4<String?, Int?, LocalDateTime?, LocalDateTime?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, Int?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, Int?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
