input ImportedMailCategoryFiltersQuery {
    size: Int
    isAsc: Boolean!
    cursor: String
    sortType: ImportedMailCategoryFiltersSortType
}

enum ImportedMailCategoryFiltersSortType {
    TITLE
    ORDER_NUMBER
}

enum ImportedMailFilterCategoryConditionOperator {
    OR
    AND
}

type ImportedMailCategoryFiltersConnection {
    nodes: [ImportedMailCategoryFilter!]!
    cursor: String
    isLast: Boolean!
}

type ImportedMailCategoryFilter {
    id: ImportedMailCategoryFilterId!
    title: String! @lazy
    subCategory: MoneyUsageSubCategory @lazy
    orderNumber: Int! @lazy
    operator: ImportedMailFilterCategoryConditionOperator! @lazy
    """
    matcherKeyを使った論理式。nullの場合はoperatorで全matcherをつないで判定する
    """
    matchExpression: String @lazy

    matchers: [ImportedMailCategoryFilterMatcher!] @lazy
}

type ImportedMailCategoryFilterMatcher {
    id: ImportedMailCategoryFilterMatcherId!
    """
    フィルタ内でmatchExpressionから参照するためのキー
    """
    matcherKey: String! @lazy
    text: String! @lazy
    dataSourceType: ImportedMailCategoryFilterDataSourceType! @lazy
    matcherType: ImportedMailCategoryFilterMatcherType! @lazy
}

enum ImportedMailCategoryFilterDataSourceType {
    MailTitle
    MailFrom
    MailHtml
    MailPlain
    Title
    ServiceName
}

enum ImportedMailCategoryFilterMatcherType {
    Include
    NotInclude
    Equal
    NotEqual
}
