/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import java.time.LocalDateTime

import net.matsudamper.money.db.schema.tables.JAdminSessions

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record3
import org.jooq.Row3
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JAdminSessionsRecord() : UpdatableRecordImpl<JAdminSessionsRecord>(JAdminSessions.ADMIN_SESSIONS), Record3<String?, LocalDateTime?, LocalDateTime?> {

    open var sessionId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var createdDate: LocalDateTime?
        set(value): Unit = set(1, value)
        get(): LocalDateTime? = get(1) as LocalDateTime?

    open var expireDatetime: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row3<String?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row3<String?, LocalDateTime?, LocalDateTime?>
    override fun valuesRow(): Row3<String?, LocalDateTime?, LocalDateTime?> = super.valuesRow() as Row3<String?, LocalDateTime?, LocalDateTime?>
    override fun field1(): Field<String?> = JAdminSessions.ADMIN_SESSIONS.SESSION_ID
    override fun field2(): Field<LocalDateTime?> = JAdminSessions.ADMIN_SESSIONS.CREATED_DATE
    override fun field3(): Field<LocalDateTime?> = JAdminSessions.ADMIN_SESSIONS.EXPIRE_DATETIME
    override fun component1(): String? = sessionId
    override fun component2(): LocalDateTime? = createdDate
    override fun component3(): LocalDateTime? = expireDatetime
    override fun value1(): String? = sessionId
    override fun value2(): LocalDateTime? = createdDate
    override fun value3(): LocalDateTime? = expireDatetime

    override fun value1(value: String?): JAdminSessionsRecord {
        set(0, value)
        return this
    }

    override fun value2(value: LocalDateTime?): JAdminSessionsRecord {
        set(1, value)
        return this
    }

    override fun value3(value: LocalDateTime?): JAdminSessionsRecord {
        set(2, value)
        return this
    }

    override fun values(value1: String?, value2: LocalDateTime?, value3: LocalDateTime?): JAdminSessionsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        return this
    }

    /**
     * Create a detached, initialised JAdminSessionsRecord
     */
    constructor(sessionId: String? = null, createdDate: LocalDateTime? = null, expireDatetime: LocalDateTime? = null): this() {
        this.sessionId = sessionId
        this.createdDate = createdDate
        this.expireDatetime = expireDatetime
        resetChangedOnNotNull()
    }
}
