/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import java.time.LocalDateTime

import net.matsudamper.money.db.schema.tables.JCategoryMailFilterConditionGroups

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record7
import org.jooq.Row7
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JCategoryMailFilterConditionGroupsRecord() : UpdatableRecordImpl<JCategoryMailFilterConditionGroupsRecord>(JCategoryMailFilterConditionGroups.CATEGORY_MAIL_FILTER_CONDITION_GROUPS), Record7<Int?, Int?, Int?, String?, Int?, LocalDateTime?, LocalDateTime?> {

    open var categoryMailFilterConditionGroupId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var categoryMailFilterId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var userId: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var title: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var categoryMailFilterConditionOperatorTypeId: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var createdDatetime: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var updateDatetime: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row7<Int?, Int?, Int?, String?, Int?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row7<Int?, Int?, Int?, String?, Int?, LocalDateTime?, LocalDateTime?>
    override fun valuesRow(): Row7<Int?, Int?, Int?, String?, Int?, LocalDateTime?, LocalDateTime?> = super.valuesRow() as Row7<Int?, Int?, Int?, String?, Int?, LocalDateTime?, LocalDateTime?>
    override fun field1(): Field<Int?> = JCategoryMailFilterConditionGroups.CATEGORY_MAIL_FILTER_CONDITION_GROUPS.CATEGORY_MAIL_FILTER_CONDITION_GROUP_ID
    override fun field2(): Field<Int?> = JCategoryMailFilterConditionGroups.CATEGORY_MAIL_FILTER_CONDITION_GROUPS.CATEGORY_MAIL_FILTER_ID
    override fun field3(): Field<Int?> = JCategoryMailFilterConditionGroups.CATEGORY_MAIL_FILTER_CONDITION_GROUPS.USER_ID
    override fun field4(): Field<String?> = JCategoryMailFilterConditionGroups.CATEGORY_MAIL_FILTER_CONDITION_GROUPS.TITLE
    override fun field5(): Field<Int?> = JCategoryMailFilterConditionGroups.CATEGORY_MAIL_FILTER_CONDITION_GROUPS.CATEGORY_MAIL_FILTER_CONDITION_OPERATOR_TYPE_ID
    override fun field6(): Field<LocalDateTime?> = JCategoryMailFilterConditionGroups.CATEGORY_MAIL_FILTER_CONDITION_GROUPS.CREATED_DATETIME
    override fun field7(): Field<LocalDateTime?> = JCategoryMailFilterConditionGroups.CATEGORY_MAIL_FILTER_CONDITION_GROUPS.UPDATE_DATETIME
    override fun component1(): Int? = categoryMailFilterConditionGroupId
    override fun component2(): Int? = categoryMailFilterId
    override fun component3(): Int? = userId
    override fun component4(): String? = title
    override fun component5(): Int? = categoryMailFilterConditionOperatorTypeId
    override fun component6(): LocalDateTime? = createdDatetime
    override fun component7(): LocalDateTime? = updateDatetime
    override fun value1(): Int? = categoryMailFilterConditionGroupId
    override fun value2(): Int? = categoryMailFilterId
    override fun value3(): Int? = userId
    override fun value4(): String? = title
    override fun value5(): Int? = categoryMailFilterConditionOperatorTypeId
    override fun value6(): LocalDateTime? = createdDatetime
    override fun value7(): LocalDateTime? = updateDatetime

    override fun value1(value: Int?): JCategoryMailFilterConditionGroupsRecord {
        set(0, value)
        return this
    }

    override fun value2(value: Int?): JCategoryMailFilterConditionGroupsRecord {
        set(1, value)
        return this
    }

    override fun value3(value: Int?): JCategoryMailFilterConditionGroupsRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): JCategoryMailFilterConditionGroupsRecord {
        set(3, value)
        return this
    }

    override fun value5(value: Int?): JCategoryMailFilterConditionGroupsRecord {
        set(4, value)
        return this
    }

    override fun value6(value: LocalDateTime?): JCategoryMailFilterConditionGroupsRecord {
        set(5, value)
        return this
    }

    override fun value7(value: LocalDateTime?): JCategoryMailFilterConditionGroupsRecord {
        set(6, value)
        return this
    }

    override fun values(value1: Int?, value2: Int?, value3: Int?, value4: String?, value5: Int?, value6: LocalDateTime?, value7: LocalDateTime?): JCategoryMailFilterConditionGroupsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        return this
    }

    /**
     * Create a detached, initialised JCategoryMailFilterConditionGroupsRecord
     */
    constructor(categoryMailFilterConditionGroupId: Int? = null, categoryMailFilterId: Int? = null, userId: Int? = null, title: String? = null, categoryMailFilterConditionOperatorTypeId: Int? = null, createdDatetime: LocalDateTime? = null, updateDatetime: LocalDateTime? = null): this() {
        this.categoryMailFilterConditionGroupId = categoryMailFilterConditionGroupId
        this.categoryMailFilterId = categoryMailFilterId
        this.userId = userId
        this.title = title
        this.categoryMailFilterConditionOperatorTypeId = categoryMailFilterConditionOperatorTypeId
        this.createdDatetime = createdDatetime
        this.updateDatetime = updateDatetime
        resetChangedOnNotNull()
    }
}
