/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import java.time.LocalDateTime

import net.matsudamper.money.db.schema.tables.JMoneyUsageCategories

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record5
import org.jooq.Row5
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JMoneyUsageCategoriesRecord() : UpdatableRecordImpl<JMoneyUsageCategoriesRecord>(JMoneyUsageCategories.MONEY_USAGE_CATEGORIES), Record5<Int?, Int?, String?, LocalDateTime?, LocalDateTime?> {

    open var moneyUsageCategoryId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var userId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var name: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var createdDatetime: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var updateDatetime: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row5<Int?, Int?, String?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row5<Int?, Int?, String?, LocalDateTime?, LocalDateTime?>
    override fun valuesRow(): Row5<Int?, Int?, String?, LocalDateTime?, LocalDateTime?> = super.valuesRow() as Row5<Int?, Int?, String?, LocalDateTime?, LocalDateTime?>
    override fun field1(): Field<Int?> = JMoneyUsageCategories.MONEY_USAGE_CATEGORIES.MONEY_USAGE_CATEGORY_ID
    override fun field2(): Field<Int?> = JMoneyUsageCategories.MONEY_USAGE_CATEGORIES.USER_ID
    override fun field3(): Field<String?> = JMoneyUsageCategories.MONEY_USAGE_CATEGORIES.NAME
    override fun field4(): Field<LocalDateTime?> = JMoneyUsageCategories.MONEY_USAGE_CATEGORIES.CREATED_DATETIME
    override fun field5(): Field<LocalDateTime?> = JMoneyUsageCategories.MONEY_USAGE_CATEGORIES.UPDATE_DATETIME
    override fun component1(): Int? = moneyUsageCategoryId
    override fun component2(): Int? = userId
    override fun component3(): String? = name
    override fun component4(): LocalDateTime? = createdDatetime
    override fun component5(): LocalDateTime? = updateDatetime
    override fun value1(): Int? = moneyUsageCategoryId
    override fun value2(): Int? = userId
    override fun value3(): String? = name
    override fun value4(): LocalDateTime? = createdDatetime
    override fun value5(): LocalDateTime? = updateDatetime

    override fun value1(value: Int?): JMoneyUsageCategoriesRecord {
        set(0, value)
        return this
    }

    override fun value2(value: Int?): JMoneyUsageCategoriesRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): JMoneyUsageCategoriesRecord {
        set(2, value)
        return this
    }

    override fun value4(value: LocalDateTime?): JMoneyUsageCategoriesRecord {
        set(3, value)
        return this
    }

    override fun value5(value: LocalDateTime?): JMoneyUsageCategoriesRecord {
        set(4, value)
        return this
    }

    override fun values(value1: Int?, value2: Int?, value3: String?, value4: LocalDateTime?, value5: LocalDateTime?): JMoneyUsageCategoriesRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        return this
    }

    /**
     * Create a detached, initialised JMoneyUsageCategoriesRecord
     */
    constructor(moneyUsageCategoryId: Int? = null, userId: Int? = null, name: String? = null, createdDatetime: LocalDateTime? = null, updateDatetime: LocalDateTime? = null): this() {
        this.moneyUsageCategoryId = moneyUsageCategoryId
        this.userId = userId
        this.name = name
        this.createdDatetime = createdDatetime
        this.updateDatetime = updateDatetime
        resetChangedOnNotNull()
    }
}
