/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import java.time.LocalDateTime

import net.matsudamper.money.db.schema.tables.JMoneyUsages

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record10
import org.jooq.Row10
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JMoneyUsagesRecord() : UpdatableRecordImpl<JMoneyUsagesRecord>(JMoneyUsages.MONEY_USAGES), Record10<Int?, Int?, Int?, String?, String?, Int?, LocalDateTime?, LocalDateTime?, LocalDateTime?, Int?> {

    open var moneyUsageId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var userId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var userMailId: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var title: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var description: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var moneyUsageSubCategoryId: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var datetime: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var createdDatetime: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    open var updateDatetime: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    open var amount: Int?
        set(value): Unit = set(9, value)
        get(): Int? = get(9) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row10<Int?, Int?, Int?, String?, String?, Int?, LocalDateTime?, LocalDateTime?, LocalDateTime?, Int?> = super.fieldsRow() as Row10<Int?, Int?, Int?, String?, String?, Int?, LocalDateTime?, LocalDateTime?, LocalDateTime?, Int?>
    override fun valuesRow(): Row10<Int?, Int?, Int?, String?, String?, Int?, LocalDateTime?, LocalDateTime?, LocalDateTime?, Int?> = super.valuesRow() as Row10<Int?, Int?, Int?, String?, String?, Int?, LocalDateTime?, LocalDateTime?, LocalDateTime?, Int?>
    override fun field1(): Field<Int?> = JMoneyUsages.MONEY_USAGES.MONEY_USAGE_ID
    override fun field2(): Field<Int?> = JMoneyUsages.MONEY_USAGES.USER_ID
    override fun field3(): Field<Int?> = JMoneyUsages.MONEY_USAGES.USER_MAIL_ID
    override fun field4(): Field<String?> = JMoneyUsages.MONEY_USAGES.TITLE
    override fun field5(): Field<String?> = JMoneyUsages.MONEY_USAGES.DESCRIPTION
    override fun field6(): Field<Int?> = JMoneyUsages.MONEY_USAGES.MONEY_USAGE_SUB_CATEGORY_ID
    override fun field7(): Field<LocalDateTime?> = JMoneyUsages.MONEY_USAGES.DATETIME
    override fun field8(): Field<LocalDateTime?> = JMoneyUsages.MONEY_USAGES.CREATED_DATETIME
    override fun field9(): Field<LocalDateTime?> = JMoneyUsages.MONEY_USAGES.UPDATE_DATETIME
    override fun field10(): Field<Int?> = JMoneyUsages.MONEY_USAGES.AMOUNT
    override fun component1(): Int? = moneyUsageId
    override fun component2(): Int? = userId
    override fun component3(): Int? = userMailId
    override fun component4(): String? = title
    override fun component5(): String? = description
    override fun component6(): Int? = moneyUsageSubCategoryId
    override fun component7(): LocalDateTime? = datetime
    override fun component8(): LocalDateTime? = createdDatetime
    override fun component9(): LocalDateTime? = updateDatetime
    override fun component10(): Int? = amount
    override fun value1(): Int? = moneyUsageId
    override fun value2(): Int? = userId
    override fun value3(): Int? = userMailId
    override fun value4(): String? = title
    override fun value5(): String? = description
    override fun value6(): Int? = moneyUsageSubCategoryId
    override fun value7(): LocalDateTime? = datetime
    override fun value8(): LocalDateTime? = createdDatetime
    override fun value9(): LocalDateTime? = updateDatetime
    override fun value10(): Int? = amount

    override fun value1(value: Int?): JMoneyUsagesRecord {
        set(0, value)
        return this
    }

    override fun value2(value: Int?): JMoneyUsagesRecord {
        set(1, value)
        return this
    }

    override fun value3(value: Int?): JMoneyUsagesRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): JMoneyUsagesRecord {
        set(3, value)
        return this
    }

    override fun value5(value: String?): JMoneyUsagesRecord {
        set(4, value)
        return this
    }

    override fun value6(value: Int?): JMoneyUsagesRecord {
        set(5, value)
        return this
    }

    override fun value7(value: LocalDateTime?): JMoneyUsagesRecord {
        set(6, value)
        return this
    }

    override fun value8(value: LocalDateTime?): JMoneyUsagesRecord {
        set(7, value)
        return this
    }

    override fun value9(value: LocalDateTime?): JMoneyUsagesRecord {
        set(8, value)
        return this
    }

    override fun value10(value: Int?): JMoneyUsagesRecord {
        set(9, value)
        return this
    }

    override fun values(value1: Int?, value2: Int?, value3: Int?, value4: String?, value5: String?, value6: Int?, value7: LocalDateTime?, value8: LocalDateTime?, value9: LocalDateTime?, value10: Int?): JMoneyUsagesRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        return this
    }

    /**
     * Create a detached, initialised JMoneyUsagesRecord
     */
    constructor(moneyUsageId: Int? = null, userId: Int? = null, userMailId: Int? = null, title: String? = null, description: String? = null, moneyUsageSubCategoryId: Int? = null, datetime: LocalDateTime? = null, createdDatetime: LocalDateTime? = null, updateDatetime: LocalDateTime? = null, amount: Int? = null): this() {
        this.moneyUsageId = moneyUsageId
        this.userId = userId
        this.userMailId = userMailId
        this.title = title
        this.description = description
        this.moneyUsageSubCategoryId = moneyUsageSubCategoryId
        this.datetime = datetime
        this.createdDatetime = createdDatetime
        this.updateDatetime = updateDatetime
        this.amount = amount
        resetChangedOnNotNull()
    }
}
