/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.records


import java.time.LocalDateTime

import net.matsudamper.money.db.schema.tables.JUserPasswords

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record4
import org.jooq.Row4
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JUserPasswordsRecord() : UpdatableRecordImpl<JUserPasswordsRecord>(JUserPasswords.USER_PASSWORDS), Record4<Int?, String?, LocalDateTime?, LocalDateTime?> {

    open var userId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var passwordHash: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var createdDatetime: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var updateDatetime: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row4<Int?, String?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row4<Int?, String?, LocalDateTime?, LocalDateTime?>
    override fun valuesRow(): Row4<Int?, String?, LocalDateTime?, LocalDateTime?> = super.valuesRow() as Row4<Int?, String?, LocalDateTime?, LocalDateTime?>
    override fun field1(): Field<Int?> = JUserPasswords.USER_PASSWORDS.USER_ID
    override fun field2(): Field<String?> = JUserPasswords.USER_PASSWORDS.PASSWORD_HASH
    override fun field3(): Field<LocalDateTime?> = JUserPasswords.USER_PASSWORDS.CREATED_DATETIME
    override fun field4(): Field<LocalDateTime?> = JUserPasswords.USER_PASSWORDS.UPDATE_DATETIME
    override fun component1(): Int? = userId
    override fun component2(): String? = passwordHash
    override fun component3(): LocalDateTime? = createdDatetime
    override fun component4(): LocalDateTime? = updateDatetime
    override fun value1(): Int? = userId
    override fun value2(): String? = passwordHash
    override fun value3(): LocalDateTime? = createdDatetime
    override fun value4(): LocalDateTime? = updateDatetime

    override fun value1(value: Int?): JUserPasswordsRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): JUserPasswordsRecord {
        set(1, value)
        return this
    }

    override fun value3(value: LocalDateTime?): JUserPasswordsRecord {
        set(2, value)
        return this
    }

    override fun value4(value: LocalDateTime?): JUserPasswordsRecord {
        set(3, value)
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: LocalDateTime?, value4: LocalDateTime?): JUserPasswordsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        return this
    }

    /**
     * Create a detached, initialised JUserPasswordsRecord
     */
    constructor(userId: Int? = null, passwordHash: String? = null, createdDatetime: LocalDateTime? = null, updateDatetime: LocalDateTime? = null): this() {
        this.userId = userId
        this.passwordHash = passwordHash
        this.createdDatetime = createdDatetime
        this.updateDatetime = updateDatetime
        resetChangedOnNotNull()
    }
}
