/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema


import kotlin.collections.List

import net.matsudamper.money.db.schema.tables.JAdminSessions
import net.matsudamper.money.db.schema.tables.JMoneyUsageCategories
import net.matsudamper.money.db.schema.tables.JMoneyUsageSubCategories
import net.matsudamper.money.db.schema.tables.JMoneyUsages
import net.matsudamper.money.db.schema.tables.JMoneyUsagesMailsRelation
import net.matsudamper.money.db.schema.tables.JUserImapSettings
import net.matsudamper.money.db.schema.tables.JUserMails
import net.matsudamper.money.db.schema.tables.JUserPasswordExtendData
import net.matsudamper.money.db.schema.tables.JUserPasswords
import net.matsudamper.money.db.schema.tables.JUserSessions
import net.matsudamper.money.db.schema.tables.JUsers

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JMoney : SchemaImpl("money", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>money</code>
         */
        val MONEY: JMoney = JMoney()
    }

    /**
     * The table <code>money.admin_sessions</code>.
     */
    val ADMIN_SESSIONS: JAdminSessions get() = JAdminSessions.ADMIN_SESSIONS

    /**
     * The table <code>money.money_usage_categories</code>.
     */
    val MONEY_USAGE_CATEGORIES: JMoneyUsageCategories get() = JMoneyUsageCategories.MONEY_USAGE_CATEGORIES

    /**
     * The table <code>money.money_usage_sub_categories</code>.
     */
    val MONEY_USAGE_SUB_CATEGORIES: JMoneyUsageSubCategories get() = JMoneyUsageSubCategories.MONEY_USAGE_SUB_CATEGORIES

    /**
     * The table <code>money.money_usages</code>.
     */
    val MONEY_USAGES: JMoneyUsages get() = JMoneyUsages.MONEY_USAGES

    /**
     * The table <code>money.money_usages_mails_relation</code>.
     */
    val MONEY_USAGES_MAILS_RELATION: JMoneyUsagesMailsRelation get() = JMoneyUsagesMailsRelation.MONEY_USAGES_MAILS_RELATION

    /**
     * The table <code>money.user_imap_settings</code>.
     */
    val USER_IMAP_SETTINGS: JUserImapSettings get() = JUserImapSettings.USER_IMAP_SETTINGS

    /**
     * The table <code>money.user_mails</code>.
     */
    val USER_MAILS: JUserMails get() = JUserMails.USER_MAILS

    /**
     * The table <code>money.user_password_extend_data</code>.
     */
    val USER_PASSWORD_EXTEND_DATA: JUserPasswordExtendData get() = JUserPasswordExtendData.USER_PASSWORD_EXTEND_DATA

    /**
     * The table <code>money.user_passwords</code>.
     */
    val USER_PASSWORDS: JUserPasswords get() = JUserPasswords.USER_PASSWORDS

    /**
     * The table <code>money.user_sessions</code>.
     */
    val USER_SESSIONS: JUserSessions get() = JUserSessions.USER_SESSIONS

    /**
     * The table <code>money.users</code>.
     */
    val USERS: JUsers get() = JUsers.USERS

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        JAdminSessions.ADMIN_SESSIONS,
        JMoneyUsageCategories.MONEY_USAGE_CATEGORIES,
        JMoneyUsageSubCategories.MONEY_USAGE_SUB_CATEGORIES,
        JMoneyUsages.MONEY_USAGES,
        JMoneyUsagesMailsRelation.MONEY_USAGES_MAILS_RELATION,
        JUserImapSettings.USER_IMAP_SETTINGS,
        JUserMails.USER_MAILS,
        JUserPasswordExtendData.USER_PASSWORD_EXTEND_DATA,
        JUserPasswords.USER_PASSWORDS,
        JUserSessions.USER_SESSIONS,
        JUsers.USERS
    )
}
