mutation AddMoneyUsage($query: AddUsageQuery!) {
    userMutation {
        addUsage(usage: $query) {
            id
        }
    }
}

query AddMoneyUsageScreen($id: ImportedMailId!) {
    user {
        importedMailAttributes {
            mail(id: $id) {
                subject
                dateTime
                forwardedInfo {
                    dateTime
                    from
                    subject
                }
                suggestUsages {
                    ...AddMoneyUsageScreenSuggestUsage
                }
                aiParseResult {
                    usages {
                        ...AddMoneyUsageScreenSuggestUsage
                    }
                }
            }
        }
    }
}

query AddMoneyUsageScreenGetSubCategory($subCategoryId: MoneyUsageSubCategoryId!) {
    user {
        moneyUsageSubCategory(input: { id: $subCategoryId }) {
            id
            name
            category {
                id
                name
            }
        }
    }
}

fragment AddMoneyUsageScreenSuggestUsage on MoneyUsageSuggest {
    title
    description
    subCategory {
        id
        name
        category {
            id
            name
        }
    }
    dateTime
    amount
}

query AddMoneyUsageScreenSameDateUsages($query: MoneyUsagesQuery!) {
    user {
        moneyUsages(query: $query) {
            nodes {
                id
                title
                amount
                date
            }
        }
    }
}
