query ImportedMailCategoryFiltersScreenPaging($query: ImportedMailCategoryFiltersQuery!) {
    user {
        importedMailCategoryFilters(query: $query) {
            cursor
            isLast
            nodes {
                id
                title
                subCategory {
                    id
                    name
                    category {
                        id
                        name
                    }
                }
            }
        }
    }
}

mutation ImportedMailCategoryFiltersScreenAddImportedMailCategory($input: AddImportedMailCategoryFilterInput!) {
    userMutation {
        addImportedMailCategoryFilter(input: $input) {
            id
        }
    }
}

mutation ImportedMailCategoryFilterUpdate($input: UpdateImportedMailCategoryFilterInput!) {
    userMutation {
        updateImportedMailCategoryFilter(input: $input) {
            ... ImportedMailCategoryFilterScreenItem
        }
    }
}

query ImportedMailCategoryFilterScreen($id: ImportedMailCategoryFilterId!) {
    user {
        importedMailCategoryFilter(id: $id) {
            ... ImportedMailCategoryFilterScreenItem
        }
    }
}

mutation ImportedMailCategoryFilterScreenAddMatcher($input: AddImportedMailCategoryFilterMatcherInput!) {
    userMutation {
        addImportedMailCategoryFilterMatcher(input: $input) {
            ... ImportedMailCategoryFilterScreenItem
        }
    }
}

mutation ImportedMailCategoryFilterScreenUpdateMatcher($input: UpdateImportedMailCategoryFilterMatcherInput!) {
    userMutation {
        updateImportedMailCategoryFilterMatcher(input: $input) {
            ... ImportedMailCategoryFilterMatcherScreenItem
        }
    }
}

mutation ImportedMailCategoryFilterScreenDeleteFilter($id: ImportedMailCategoryFilterId!) {
    userMutation {
        deleteImportedMailCategoryFilter(id: $id)
    }
}

mutation ImportedMailCategoryFilterScreenDeleteMatcher($id: ImportedMailCategoryFilterMatcherId!) {
    userMutation {
        deleteImportedMailCategoryFilterMatcher(id: $id)
    }
}

fragment ImportedMailCategoryFilterScreenItem on ImportedMailCategoryFilter {
    id
    title
    matchExpression
    subCategory {
        id
        name
        category {
            id
            name
        }
    }
    matchers {
        ... ImportedMailCategoryFilterMatcherScreenItem
    }
}

fragment ImportedMailCategoryFilterMatcherScreenItem on ImportedMailCategoryFilterMatcher {
    id
    matcherKey
    matcherType
    dataSourceType
    text
}
