query ImportedMailScreen($id: ImportedMailId!) {
    user {
        importedMailAttributes {
            mail(id: $id) {
                id
                from
                hasPlain
                hasHtml
                subject
                dateTime
                usages {
                    id
                    amount
                    title
                    description
                    date
                    moneyUsageSubCategory {
                        id
                        name
                        category {
                            id
                            name
                        }
                    }
                }
                suggestUsages {
                    ...ImportedMailScreenSuggestUsage
                }
                aiParseResult {
                    status
                    errorMessage
                    usages {
                        ...ImportedMailScreenSuggestUsage
                    }
                }
            }
        }
    }
}

mutation ImportedMailScreenDeleteMail($id: ImportedMailId!) {
    userMutation {
        deleteImportedMail(id: $id)
    }
}

mutation ImportedMailScreenStartAiParse($id: ImportedMailId!) {
    userMutation {
        startImportedMailAiParse(id: $id) {
            isSuccess
            error
        }
    }
}

fragment ImportedMailScreenSuggestUsage on MoneyUsageSuggest {
    title
    serviceName
    description
    dateTime
    amount
    subCategory {
        id
        name
        category {
            id
            name
        }
    }
}
