query NotificationUsageCategoryFilters($query: ImportedMailCategoryFiltersQuery!) {
    user {
        importedMailCategoryFilters(query: $query) {
            nodes {
                id
                orderNumber
                operator
                matchExpression
                subCategory {
                    id
                    name
                    category {
                        name
                    }
                }
                matchers {
                    id
                    matcherKey
                    text
                    dataSourceType
                    matcherType
                }
            }
        }
    }
}
