query NotificationUsageCategoryFilters($query: ImportedMailCategoryFiltersQuery!) {
    user {
        importedMailCategoryFilters(query: $query) {
            nodes {
                id
                orderNumber
                operator
                descriptionSuffix
                subCategory {
                    id
                    name
                    category {
                        name
                    }
                }
                conditions {
                    id
                    text
                    dataSourceType
                    conditionType
                }
            }
        }
    }
}
