/*
 * This file is generated by jOOQ.
 */
package net.matsudamper.money.db.schema.tables.references


import net.matsudamper.money.db.schema.tables.JAdminSessions
import net.matsudamper.money.db.schema.tables.JMoneyUsageCategories
import net.matsudamper.money.db.schema.tables.JMoneyUsageSubCategories
import net.matsudamper.money.db.schema.tables.JMoneyUsages
import net.matsudamper.money.db.schema.tables.JUserImapSettings
import net.matsudamper.money.db.schema.tables.JUserMails
import net.matsudamper.money.db.schema.tables.JUserPasswordExtendData
import net.matsudamper.money.db.schema.tables.JUserPasswords
import net.matsudamper.money.db.schema.tables.JUserSessions
import net.matsudamper.money.db.schema.tables.JUsers



/**
 * The table <code>money.admin_sessions</code>.
 */
val ADMIN_SESSIONS: JAdminSessions = JAdminSessions.ADMIN_SESSIONS

/**
 * The table <code>money.money_usage_categories</code>.
 */
val MONEY_USAGE_CATEGORIES: JMoneyUsageCategories = JMoneyUsageCategories.MONEY_USAGE_CATEGORIES

/**
 * The table <code>money.money_usage_sub_categories</code>.
 */
val MONEY_USAGE_SUB_CATEGORIES: JMoneyUsageSubCategories = JMoneyUsageSubCategories.MONEY_USAGE_SUB_CATEGORIES

/**
 * The table <code>money.money_usages</code>.
 */
val MONEY_USAGES: JMoneyUsages = JMoneyUsages.MONEY_USAGES

/**
 * The table <code>money.user_imap_settings</code>.
 */
val USER_IMAP_SETTINGS: JUserImapSettings = JUserImapSettings.USER_IMAP_SETTINGS

/**
 * The table <code>money.user_mails</code>.
 */
val USER_MAILS: JUserMails = JUserMails.USER_MAILS

/**
 * The table <code>money.user_password_extend_data</code>.
 */
val USER_PASSWORD_EXTEND_DATA: JUserPasswordExtendData = JUserPasswordExtendData.USER_PASSWORD_EXTEND_DATA

/**
 * The table <code>money.user_passwords</code>.
 */
val USER_PASSWORDS: JUserPasswords = JUserPasswords.USER_PASSWORDS

/**
 * The table <code>money.user_sessions</code>.
 */
val USER_SESSIONS: JUserSessions = JUserSessions.USER_SESSIONS

/**
 * The table <code>money.users</code>.
 */
val USERS: JUsers = JUsers.USERS
