on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: ./gradlew assembleRelease

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if gh release view "$TAG" >/dev/null 2>&1; then
            gh release upload "$TAG" app/build/outputs/apk/release/*.apk --clobber
          else
            gh release create "$TAG" app/build/outputs/apk/release/*.apk --title "$TAG" --notes ""
          fi
  
