name: Docker Release
on:
  push:
    tags:
      - 'v*'

permissions:
  packages: write
  contents: write

concurrency:
  group: docker-release
  cancel-in-progress: false

jobs:
  docker-release-build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SERVER_HOST: ""
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew :backend:build
      - run: ./gradlew :frontend:app:jsBrowserDevelopmentExecutableDistribution

      - name: Upload backend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-distribution
          path: backend/build/distributions/backend-jvm.tar

      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-distribution
          path: frontend/app/build/dist/js/developmentExecutable

  docker-push:
    runs-on: ubuntu-latest
    needs: docker-release-build
    steps:
      - uses: actions/checkout@v5

      - name: Download backend artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-distribution
          path: backend/build/distributions

      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-distribution
          path: frontend/app/build/dist/js/developmentExecutable

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=raw,value=latest
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  github-release:
    runs-on: ubuntu-latest
    needs: docker-release-build
    steps:
      - name: Download backend artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-distribution

      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-distribution
          path: frontend-dist

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            backend-jvm.tar
            frontend-dist
